-- Up Migration
-- Union binding conflict log app.union_binding_conflicts (30151 落库; BR-ID-18 relation_conflict,
-- BR-ID-19 细则「并发绑定」, BR-ATTR-17 / 18 time-point lookup; 规划/12 联盟绑定时序图「写冲突日志，
-- 原绑定不变」; ADR-0001 §4). Task B1-06y. Writer: linking (B1-06z writes a row for every 30151 and
-- resolves the user's open rows when a binding becomes active). 规划/04 §3.2 has no shape for this
-- table yet; after merge the planning session writes it back (precedent B1-06r).
-- Compatibility: additive (one new table, its constraints, indexes, triggers and grants; nothing
-- existing changes). Recovery: restore from backup; no down migration.
--
-- One row per refused authorization (30151). Columns:
--   id                uuid         UUIDv7 generated by the application (no SQL default, rule 6).
--   app_id, user_id   the user whose authorization was refused (FK app.users (app_id, id)).
--   platform          the union platform (contracts/enums/platform.yaml platform; named CHECK).
--   union_account_id  our union account the authorization was for (FK app.union_accounts
--                     (app_id, platform, id), precedent 0015 union_pids / 0018 union_bindings:
--                     same app and the row's platform equals the account's). The platform keeps
--                     its own named CHECK as well (orchestrator ruling D7-20): a CHECK is evaluated
--                     when the row is formed, before the foreign key triggers, so an unknown
--                     platform is still rejected as 23514 and only a known platform that differs
--                     from the account's is rejected by the foreign key (23503).
--   kind              occupied (relation held by another user's active binding) / cooling (held
--                     by another user's binding in cooldown) / rebind (this user already has a
--                     different unreleased binding on this platform).
--   occurred_at       when the conflict happened (application clock, no SQL default).
--   resolved_at, resolution  both NULL while unresolved. resolution = bound_active when this
--                     user's binding on this platform later becomes active (same transaction marks
--                     all open rows of the user and platform); already_active when the user already
--                     had an active binding at write time (resolved_at = occurred_at, the
--                     authorization is still refused). Application clock, no SQL default.
-- Nothing about the counterparty is stored: no other user_id, no relation_id, no token, nick,
-- avatar or account name (the log is read for relation_conflict and recovery, never shown).
--
-- Reads: "unresolved now" uses the partial index (app_id, user_id, platform) WHERE resolved_at IS
-- NULL; "unresolved at attr_at" (occurred_at <= attr_at AND (resolved_at IS NULL OR resolved_at >
-- attr_at)) uses the index (app_id, user_id, platform, occurred_at).
--
-- Immutability (db/AGENTS.md rules 4 and 8, precedent 0018 / 0020): couli_app gets SELECT,
-- INSERT and column UPDATE (resolved_at, resolution) only, no DELETE. A BEFORE UPDATE trigger
-- rejects (restrict_violation) any change of the other columns and any change of an already
-- resolved row, so a row is resolved at most once and never reopened; a BEFORE DELETE trigger
-- (app.reject_update_delete from 0003) rejects DELETE for every role. couli_readonly gets SELECT.
--
-- Timeouts: a new empty table; CREATE TABLE / INDEX and the FK validation are instant, but the
-- FKs take SHARE ROW EXCLUSIVE on app.users and app.union_accounts. 5s lock wait so a blocked
-- deploy fails fast instead of queueing traffic behind it, 30s overall as a ceiling.
SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '30s';

CREATE TABLE app.union_binding_conflicts (
  id               uuid NOT NULL,
  app_id           text NOT NULL,
  user_id          uuid NOT NULL,
  platform         text NOT NULL,
  union_account_id uuid NOT NULL,
  kind             text NOT NULL,
  occurred_at      timestamptz NOT NULL,
  resolved_at      timestamptz,
  resolution       text,
  CONSTRAINT union_binding_conflicts_pkey PRIMARY KEY (id),
  CONSTRAINT union_binding_conflicts_user_fkey FOREIGN KEY (app_id, user_id)
    REFERENCES app.users (app_id, id),
  CONSTRAINT union_binding_conflicts_account_fkey FOREIGN KEY (app_id, platform, union_account_id)
    REFERENCES app.union_accounts (app_id, platform, id),
  CONSTRAINT union_binding_conflicts_platform_check CHECK (
    platform IN ('taobao', 'jd', 'pdd', 'meituan', 'vip', 'douyin', 'eleme', 'kuaishou', 'suning')
  ),
  CONSTRAINT union_binding_conflicts_kind_check
    CHECK (kind IN ('occupied', 'cooling', 'rebind')),
  CONSTRAINT union_binding_conflicts_resolution_check
    CHECK (resolution IN ('bound_active', 'already_active')),
  CONSTRAINT union_binding_conflicts_resolution_pair_check
    CHECK ((resolved_at IS NULL) = (resolution IS NULL)),
  CONSTRAINT union_binding_conflicts_resolved_order_check CHECK (resolved_at >= occurred_at)
);

CREATE INDEX union_binding_conflicts_unresolved_idx
  ON app.union_binding_conflicts (app_id, user_id, platform)
  WHERE resolved_at IS NULL;

CREATE INDEX union_binding_conflicts_history_idx
  ON app.union_binding_conflicts (app_id, user_id, platform, occurred_at);

CREATE FUNCTION app.reject_union_binding_conflict_rewrite()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog, pg_temp
AS $$
BEGIN
  IF ROW(NEW.id, NEW.app_id, NEW.user_id, NEW.platform, NEW.union_account_id, NEW.kind,
         NEW.occurred_at)
      IS DISTINCT FROM
      ROW(OLD.id, OLD.app_id, OLD.user_id, OLD.platform, OLD.union_account_id, OLD.kind,
          OLD.occurred_at)
    OR ((OLD.resolved_at IS NOT NULL OR OLD.resolution IS NOT NULL)
      AND ROW(NEW.resolved_at, NEW.resolution) IS DISTINCT FROM ROW(OLD.resolved_at, OLD.resolution))
  THEN
    RAISE EXCEPTION 'union_binding_conflicts are immutable and resolve at most once'
      USING ERRCODE = 'restrict_violation';
  END IF;
  RETURN NEW;
END
$$;

REVOKE ALL ON FUNCTION app.reject_union_binding_conflict_rewrite() FROM PUBLIC;

CREATE TRIGGER union_binding_conflicts_no_rewrite
  BEFORE UPDATE ON app.union_binding_conflicts
  FOR EACH ROW EXECUTE FUNCTION app.reject_union_binding_conflict_rewrite();

CREATE TRIGGER union_binding_conflicts_no_delete
  BEFORE DELETE ON app.union_binding_conflicts
  FOR EACH ROW EXECUTE FUNCTION app.reject_update_delete();

GRANT SELECT, INSERT ON app.union_binding_conflicts TO couli_app;
GRANT UPDATE (resolved_at, resolution) ON app.union_binding_conflicts TO couli_app;
GRANT SELECT ON app.union_binding_conflicts TO couli_readonly;
