/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AdminPermissions {
  admin_id: string;
  app_id: string;
  created_at: Generated<Timestamp>;
  granted_at: Timestamp;
  granted_by: string;
  id: Generated<ColumnType<bigint, bigint, bigint>>;
  permission_key: string;
}

export interface AdminUsers {
  app_id: string;
  created_at: Generated<Timestamp>;
  failed_login_count: Generated<number>;
  id: string;
  is_super: boolean;
  locked_until: Timestamp | null;
  login_name: string;
  password_hash: string;
  password_must_change: Generated<boolean>;
  row_version: Generated<number>;
  status: string;
  totp_bound_at: Timestamp | null;
  totp_last_step: ColumnType<bigint, bigint, bigint> | null;
  totp_secret_cipher: Buffer | null;
  updated_at: Generated<Timestamp>;
  verify_phone_cipher: Buffer | null;
  verify_phone_hmac: string | null;
  verify_phone_set_at: Timestamp | null;
}

export interface AgentCards {
  app_id: string;
  card_id: string;
  created_at: Generated<Timestamp>;
  data: Json;
  fallback_text: string;
  id: string;
  link_id: string | null;
  run_id: string;
  schema_version: number;
  session_id: string;
  type: string;
}

export interface AgentMessages {
  app_id: string;
  badcase: Generated<boolean>;
  card_ids: Generated<string[]>;
  client_msg_id: string | null;
  created_at: Generated<Timestamp>;
  feedback: string | null;
  feedback_at: Timestamp | null;
  id: string;
  report_handled_at: Timestamp | null;
  report_handler_id: string | null;
  report_note: string | null;
  report_reason: string | null;
  report_status: string | null;
  reported: Generated<boolean>;
  reported_at: Timestamp | null;
  role: string;
  row_version: Generated<number>;
  run_id: string | null;
  session_id: string;
  text: string | null;
  updated_at: Generated<Timestamp>;
}

export interface AgentResultSets {
  app_id: string;
  conditions: Json;
  created_at: Generated<Timestamp>;
  id: string;
  run_id: string;
}

export interface AgentRuns {
  accepted_at: Timestamp;
  app_id: string;
  cancel_requested_at: Timestamp | null;
  card_delivered: Generated<boolean>;
  cost_mfen: ColumnType<bigint, bigint, bigint> | null;
  created_at: Generated<Timestamp>;
  deadline_at: Timestamp | null;
  end_draft: Json | null;
  end_reason: string | null;
  ended_at: Timestamp | null;
  filter_hits: Generated<string[]>;
  final_event: Json | null;
  finalize_hold: string | null;
  finalize_hold_at: Timestamp | null;
  finish_reason: string | null;
  id: string;
  input_tokens: number | null;
  intent: string | null;
  judge_model: string | null;
  latency_ms: number | null;
  model: string | null;
  model_snapshot: string | null;
  output_filtered: Generated<boolean>;
  output_tokens: number | null;
  output_truncated: Generated<boolean>;
  page_guide_reject_reason: string | null;
  price_version: string | null;
  prompt_version: string;
  quota_subjects: string[];
  result_check_provider: string | null;
  row_version: Generated<number>;
  session_id: string;
  settle_result: string | null;
  settled_at: Timestamp | null;
  ttft_ms: number | null;
  updated_at: Generated<Timestamp>;
  user_text: string | null;
}

export interface AgentSessions {
  app_id: string;
  card_seq: Generated<number>;
  created_at: Generated<Timestamp>;
  device_id: string;
  expired_at: Timestamp | null;
  id: string;
  last_active_at: Timestamp;
  row_version: Generated<number>;
  run_lock_expires_at: Timestamp | null;
  run_lock_run_id: string | null;
  started_at: Timestamp;
  updated_at: Generated<Timestamp>;
  user_id: string | null;
}

export interface AgentToolCalls {
  app_id: string;
  args: Json | null;
  created_at: Generated<Timestamp>;
  id: string;
  latency_ms: number | null;
  name: string;
  result_digest: string | null;
  run_id: string;
  seq: number;
  status: string;
}

export interface Appeals {
  app_id: string;
  closed_at: Timestamp | null;
  content: string;
  created_at: Generated<Timestamp>;
  deadline_at: Timestamp;
  handler_id: string | null;
  id: string;
  prev_risk_state: string | null;
  related_phone_hmac: string | null;
  request_type: string | null;
  row_version: Generated<number>;
  status: string;
  target_id: string;
  target_type: string;
  updated_at: Generated<Timestamp>;
  user_id: string | null;
}

export interface AppVersions {
  app_id: string;
  channel: string;
  created_at: Generated<Timestamp>;
  default_store: string;
  id: string;
  latest_version: string;
  min_supported_version: string | null;
  platform: string;
  recommended_version: string | null;
  row_version: Generated<number>;
  store_listings: Json;
  store_url: string;
  update_notes: string;
  update_title: string;
  updated_at: Generated<Timestamp>;
}

export interface Articles {
  app_id: string;
  body: string;
  category: string;
  created_at: Generated<Timestamp>;
  id: string;
  notice_closable: boolean;
  notice_content_version: Generated<number>;
  notice_end_at: Timestamp | null;
  published_at: Timestamp | null;
  row_version: Generated<number>;
  status: string;
  title: string;
  updated_at: Generated<Timestamp>;
  version: Generated<number>;
}

export interface AuditLogs {
  action: string;
  admin_id: string;
  after: Json | null;
  app_id: string;
  at: Timestamp;
  before: Json | null;
  created_at: Generated<Timestamp>;
  id: Generated<ColumnType<bigint, bigint, bigint>>;
  ip: string | null;
  target: string | null;
}

export interface Blocklist {
  app_id: string;
  created_at: Generated<Timestamp>;
  created_by: string;
  dimension: string;
  end_at: Timestamp | null;
  expire_at: Timestamp | null;
  id: string;
  platform: string | null;
  reason: string | null;
  row_version: Generated<number>;
  start_at: Timestamp | null;
  status: string;
  union_account_id: string | null;
  updated_at: Generated<Timestamp>;
  value: string | null;
  value_hmac: string | null;
  violation_type: string;
}

export interface CategoryBlocklist {
  app_id: string;
  category_id: string;
  created_at: Generated<Timestamp>;
  id: string;
  keyword: string | null;
  platform: string;
  reason: string;
  status: string;
  updated_at: Generated<Timestamp>;
  updated_by: string;
}

export interface ConfigItems {
  app_id: string;
  created_at: Generated<Timestamp>;
  key: string;
  row_version: Generated<number>;
  updated_at: Generated<Timestamp>;
  updated_by: string;
  value: Json;
  version: Generated<number>;
}

export interface ConsentRecords {
  accepted: boolean;
  app_id: string;
  channel: string;
  client_at: Timestamp;
  created_at: Generated<Timestamp>;
  device_id: string | null;
  id: Generated<ColumnType<bigint, bigint, bigint>>;
  server_at: Timestamp;
  signer_snapshot: Json | null;
  subject_type: string;
  text_sha256: string | null;
  type: string;
  user_id: string | null;
  version: number;
}

export interface DeviceRegistrations {
  app_id: string;
  created_at: Generated<Timestamp>;
  device_hash: string;
  merged_into_user_id: string | null;
  register_method: string;
  user_id: string;
}

export interface Devices {
  app_id: string;
  app_version: string;
  created_at: Generated<Timestamp>;
  device_hash: string;
  id: string;
  id_source: string;
  install_secret_cipher: Buffer;
  last_login_sid: string | null;
  last_seen_at: Timestamp;
  platform: string;
  revoked_at: Timestamp | null;
  row_version: Generated<number>;
  updated_at: Generated<Timestamp>;
  user_id: string | null;
}

export interface EventLog {
  app_id: string;
  created_at: Generated<Timestamp>;
  event_id: string;
  id: Generated<ColumnType<bigint, bigint, bigint>>;
  name: string;
  occurred_at: Timestamp;
  payload: Json;
}

export interface IdempotencyKeys {
  app_id: string;
  created_at: Generated<Timestamp>;
  expire_at: Timestamp;
  id: Generated<ColumnType<bigint, bigint, bigint>>;
  key: string;
  method: string;
  path: string;
  request_hash: string | null;
  response: Json | null;
  status: string;
  subject: string;
  user_id: string | null;
}

export interface InboxMessages {
  app_id: string;
  body: string;
  code: string;
  created_at: Generated<Timestamp>;
  message_id: string;
  read_at: Timestamp | null;
  route: Json | null;
  row_version: Generated<number>;
  title: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface LinkLogs {
  agent_message_id: string | null;
  agent_session_id: string | null;
  app_id: string;
  cache_hit: Generated<boolean>;
  client: string | null;
  created_at: Generated<Timestamp>;
  event: string;
  expired: Generated<boolean>;
  id: Generated<ColumnType<bigint, bigint, bigint>>;
  latency_ms: number | null;
  link_id: string | null;
  model: string | null;
  no_rebate: Generated<boolean>;
  no_rebate_reason: string | null;
  opener_user_id: string | null;
  pid: string | null;
  pid_scene: string | null;
  platform: string | null;
  product_key: string | null;
  prompt_version: string | null;
  quoted_price_fen: ColumnType<bigint, bigint, bigint> | null;
  raw_item_id: string | null;
  relation_id: string | null;
  result_code: number;
  scene: string | null;
  shop_id: string | null;
  spm: string | null;
  user_id: string | null;
}

export interface LinkOpenAttempts {
  app_id: string;
  attempt_id: string;
  created_at: Generated<Timestamp>;
  dismissed_at: Timestamp | null;
  jump_reported_at: Timestamp | null;
  link_id: string;
  opened_at: Timestamp;
  row_version: Generated<number>;
  updated_at: Generated<Timestamp>;
  user_id: string | null;
}

export interface Links {
  agent_card_id: string | null;
  agent_session_id: string | null;
  app_id: string;
  cache_hit: Generated<boolean>;
  convert_result: Buffer | null;
  created_at: Generated<Timestamp>;
  device_id: string | null;
  entry_source: string | null;
  expire_at: Timestamp;
  identity_snapshot: Json | null;
  link_id: string;
  pid: string | null;
  pid_scene: string | null;
  platform: string;
  product_key: string | null;
  promo_url: string | null;
  promo_url_fetched_at: Timestamp | null;
  quoted_at: Timestamp | null;
  quoted_coupon_fen: ColumnType<bigint, bigint, bigint> | null;
  quoted_coupon_id: string | null;
  quoted_final_price_fen: ColumnType<bigint, bigint, bigint> | null;
  raw_fetched_at: Timestamp | null;
  raw_item_id: string | null;
  row_version: Generated<number>;
  scene: string;
  sub_scene: string | null;
  updated_at: Generated<Timestamp>;
  user_id: string | null;
}

export interface LoginLogs {
  app_id: string;
  created_at: Generated<Timestamp>;
  device_hash: string | null;
  device_id_hash: string;
  id: Generated<ColumnType<bigint, bigint, bigint>>;
  ip: string;
  method: string;
  user_id: string;
}

export interface OrderKeys {
  app_id: string;
  attr_at: Timestamp;
  created_at: Generated<Timestamp>;
  order_id: string;
  platform: string;
  sub_order_id: string;
}

export interface OrderRights {
  amount_fen: ColumnType<bigint, bigint, bigint> | null;
  app_id: string;
  created_at: Generated<Timestamp>;
  deduction_commission_fen: ColumnType<bigint, bigint, bigint> | null;
  id: string;
  occurred_at: Timestamp;
  order_id: string;
  platform_rights_no: string | null;
  row_version: Generated<number>;
  source: string;
  status: string;
  type: string;
  updated_at: Generated<Timestamp>;
}

export interface Orders {
  activity_type: string | null;
  agent_session_id: string | null;
  app_id: string;
  attr_at: Timestamp;
  base_fen: ColumnType<bigint, bigint, bigint> | null;
  booked_base_fen: ColumnType<bigint, bigint, bigint> | null;
  booked_n_fen: ColumnType<bigint, bigint, bigint> | null;
  buy_type: string | null;
  commission_rate_bp: number | null;
  commission_rate_max_bp: number | null;
  commission_rate_min_bp: number | null;
  commission_version: Generated<number>;
  content_hash: string | null;
  created_at: Generated<Timestamp>;
  credit_requires_settle: Generated<boolean>;
  credited_at: Timestamp | null;
  custom_params: string | null;
  deposit_paid_at: Timestamp | null;
  diff_reason_code: string | null;
  est_commission_fen: ColumnType<bigint, bigint, bigint> | null;
  hold: Generated<boolean>;
  hold_reason: string | null;
  image_url: string | null;
  initial_est_fen: ColumnType<bigint, bigint, bigint> | null;
  is_presale: Generated<boolean>;
  is_price_compare: boolean | null;
  link_id: string | null;
  locked: Generated<boolean>;
  n_total_fen: ColumnType<bigint, bigint, bigint> | null;
  order_id: string;
  paid_at: Timestamp | null;
  paid_at_source: string | null;
  parent_order_id: string | null;
  pay_amount_fen: ColumnType<bigint, bigint, bigint> | null;
  pid: string | null;
  platform: string;
  platform_est_profit_fen: ColumnType<bigint, bigint, bigint> | null;
  platform_modified_at: Timestamp | null;
  platform_received_at: Timestamp | null;
  platform_status: string;
  pre_base_deduct_fen: ColumnType<bigint, bigint, bigint> | null;
  product_key: string | null;
  quantity: number | null;
  raw_item_id: string;
  raw_payload_id: ColumnType<bigint, bigint, bigint> | null;
  reason: string | null;
  reason_sub: string | null;
  rebate_status: Generated<string>;
  received_at: Timestamp | null;
  received_synced_at: Timestamp | null;
  refunded_quantity: number | null;
  refunded_quantity_at_credit: number | null;
  relation_id: string | null;
  rights_pending: Generated<boolean>;
  row_version: Generated<number>;
  scene_basis: string | null;
  settle_commission_fen: ColumnType<bigint, bigint, bigint> | null;
  settle_period: string | null;
  settled_at: Timestamp | null;
  shop_id: string | null;
  shop_type: string | null;
  source_match: string | null;
  source_scene: string | null;
  sub_order_id: string;
  sub_union_id: string | null;
  subsidy_commission_fen: ColumnType<bigint, bigint, bigint> | null;
  title: string | null;
  union_settled_at: Timestamp | null;
  updated_at: Generated<Timestamp>;
  user_basis: string | null;
  user_id: string | null;
}

export interface OrderSettlements {
  app_id: string;
  content_hash: string;
  created_at: Generated<Timestamp>;
  order_id: string;
  seq: number;
  settle_commission_fen: ColumnType<bigint, bigint, bigint>;
  settled_at: Timestamp;
  source: string;
}

export interface PayoutAccountChanges {
  app_id: string;
  changed_at: Timestamp;
  created_at: Generated<Timestamp>;
  id: Generated<ColumnType<bigint, bigint, bigint>>;
  new_hmac: string;
  new_payout_method: string;
  old_hmac: string;
  old_payout_method: string;
  operator: string;
  user_id: string;
}

export interface PayoutAccounts {
  alipay_hmac: string | null;
  alipay_logon_id_cipher: Buffer | null;
  app_id: string;
  bank_card_hmac: string | null;
  bank_card_no_cipher: Buffer | null;
  bank_name: string | null;
  card_bin: string | null;
  created_at: Generated<Timestamp>;
  id: string;
  is_current: boolean;
  payee_name: string;
  payout_method: string;
  row_version: Generated<number>;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface PayoutAccountVerifyAttempts {
  app_id: string;
  created_at: Generated<Timestamp>;
  id: string;
  idempotency_key: string | null;
  origin_action: string;
  request_fingerprint: string;
  reserved_at: Timestamp;
  resolved_at: Timestamp | null;
  row_version: Generated<number>;
  status: string;
  unknown_at: Timestamp | null;
  updated_at: Generated<Timestamp>;
  user_id: string;
  vendor_request_id: string;
  verify_date: Timestamp;
}

export interface Platforms {
  code: string;
  convert_support: string;
  created_at: Generated<Timestamp>;
  key_prefix: string | null;
  key_stability: string;
  order_sync_support: string;
  search_support: string;
  stage: string;
  updated_at: Generated<Timestamp>;
}

export interface ProcessedEvents {
  consumer: string;
  created_at: Generated<Timestamp>;
  event_id: string;
}

export interface ProductKeyAliases {
  adr_id: string;
  created_at: Generated<Timestamp>;
  new_key: string;
  old_key: string;
  reason: string;
}

export interface ProductRefs {
  app_id: string;
  canonical_url: string | null;
  created_at: Generated<Timestamp>;
  platform: string;
  product_key: string;
  raw_fetched_at: Timestamp;
  raw_item_id: string;
  refreshed_at: Timestamp;
  shop_id: string | null;
  shop_type: string | null;
  source: string;
  title: string;
  updated_at: Generated<Timestamp>;
}

export interface PushTokens {
  acquired_by_move_at: Timestamp | null;
  app_id: string;
  bound_sid: string | null;
  created_at: Generated<Timestamp>;
  device_id: string;
  frozen_until: Timestamp | null;
  id: string;
  provider: string;
  revoked_at: Timestamp | null;
  row_version: Generated<number>;
  token: string;
  token_set_at: Timestamp;
  updated_at: Generated<Timestamp>;
  user_id: string | null;
}

export interface RefreshTokens {
  app_id: string;
  created_at: Generated<Timestamp>;
  expire_at: Timestamp;
  id: string;
  parent_hash: string | null;
  rotated_at: Timestamp | null;
  sid: string;
  token_hash: string;
  updated_at: Generated<Timestamp>;
}

export interface RiskHits {
  amount_fen: ColumnType<bigint, bigint, bigint> | null;
  app_id: string;
  created_at: Generated<Timestamp>;
  dimension: string;
  id: Generated<ColumnType<bigint, bigint, bigint>>;
  ref_id: string;
  ref_type: string;
  related_phone_hmac: string | null;
  related_phone_masked: string | null;
  request_type: string | null;
  risk_action: string;
  rule_id: string;
  user_id: string | null;
  value_hmac: string;
}

export interface RiskRules {
  app_id: string;
  conditions: Json;
  created_at: Generated<Timestamp>;
  id: string;
  risk_action: string;
  row_version: Generated<number>;
  rule_id: string;
  scene: string;
  status: string;
  updated_at: Generated<Timestamp>;
  version: number;
}

export interface Sessions {
  app_id: string;
  created_at: Generated<Timestamp>;
  device_id: string;
  id: string;
  revoke_reason: string | null;
  revoked_at: Timestamp | null;
  sid: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface UnionAccounts {
  account_name: string;
  alert_stage: Generated<string>;
  app_id: string;
  auth_expires_at: Timestamp | null;
  auth_renewed_at: Timestamp | null;
  auth_renewed_by: string | null;
  auth_status: string;
  created_at: Generated<Timestamp>;
  id: string;
  last_probe_at: Timestamp | null;
  last_probe_error: string | null;
  last_probe_ok: boolean | null;
  platform: string;
  row_version: Generated<number>;
  status: string;
  sync_start_at: Timestamp | null;
  updated_at: Generated<Timestamp>;
}

export interface UnionAuthSessions {
  app_id: string;
  auth_app_refs: Json | null;
  auth_methods: string[] | null;
  client: string;
  created_at: Generated<Timestamp>;
  device_id: string;
  expire_at: Timestamp;
  link_id: string | null;
  mode: string;
  platform: string;
  state: string;
  used_at: Timestamp | null;
  user_id: string;
}

export interface UnionBindings {
  app_id: string;
  blocked_reason: string | null;
  bound_at: Timestamp | null;
  cooldown_until: Timestamp | null;
  created_at: Generated<Timestamp>;
  id: string;
  pdd_custom: string | null;
  platform: string;
  reason: string | null;
  relation_id: string | null;
  released_at: Timestamp | null;
  row_version: Generated<number>;
  special_id: string | null;
  status: string;
  union_account_id: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface UnionCredentials {
  access_token_cipher: Buffer;
  app_id: string;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp | null;
  id: string;
  is_current: boolean;
  refresh_token_cipher: Buffer | null;
  union_account_id: string;
  updated_at: Generated<Timestamp>;
}

export interface UnionPids {
  app_id: string;
  created_at: Generated<Timestamp>;
  hjy_ignore_confirmed_at: Timestamp | null;
  hjy_ignore_evidence_path: string | null;
  id: string;
  pid: string;
  pid_scene: string;
  platform: string;
  row_version: Generated<number>;
  site_id: string | null;
  status: Generated<string>;
  union_account_id: string;
  updated_at: Generated<Timestamp>;
}

export interface UserOauth {
  app_id: string;
  created_at: Generated<Timestamp>;
  id: string;
  merged_from_user_id: string | null;
  open_id: string | null;
  provider: string;
  row_version: Generated<number>;
  union_id: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface UserRiskState {
  app_id: string;
  changed_at: Timestamp;
  changed_by: string;
  created_at: Generated<Timestamp>;
  frozen_until: Timestamp | null;
  reason: string | null;
  reason_category: string | null;
  row_version: Generated<number>;
  state: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface Users {
  app_id: string;
  attr_code: string;
  avatar: string;
  created_at: Generated<Timestamp>;
  deleted_reason: string | null;
  id: string;
  invite_code: string;
  level: string;
  nickname: string;
  nickname_change_count: Generated<number>;
  nickname_change_month: string | null;
  parent_bind_source: string | null;
  parent_bound_at: Timestamp | null;
  parent_id: string | null;
  personalization_off: Generated<boolean>;
  phone_cipher: Buffer | null;
  phone_hmac: string | null;
  register_method: string;
  registered_channel: string | null;
  row_version: Generated<number>;
  self_bind_used: Generated<boolean>;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface UserTipReads {
  app_id: string;
  created_at: Generated<Timestamp>;
  platform: string;
  read_at: Timestamp;
  tip_key: string;
  user_id: string;
}

export interface DB {
  admin_permissions: AdminPermissions;
  admin_users: AdminUsers;
  agent_cards: AgentCards;
  agent_messages: AgentMessages;
  agent_result_sets: AgentResultSets;
  agent_runs: AgentRuns;
  agent_sessions: AgentSessions;
  agent_tool_calls: AgentToolCalls;
  app_versions: AppVersions;
  appeals: Appeals;
  articles: Articles;
  audit_logs: AuditLogs;
  blocklist: Blocklist;
  category_blocklist: CategoryBlocklist;
  config_items: ConfigItems;
  consent_records: ConsentRecords;
  device_registrations: DeviceRegistrations;
  devices: Devices;
  event_log: EventLog;
  idempotency_keys: IdempotencyKeys;
  inbox_messages: InboxMessages;
  link_logs: LinkLogs;
  link_open_attempts: LinkOpenAttempts;
  links: Links;
  login_logs: LoginLogs;
  order_keys: OrderKeys;
  order_rights: OrderRights;
  order_settlements: OrderSettlements;
  orders: Orders;
  payout_account_changes: PayoutAccountChanges;
  payout_account_verify_attempts: PayoutAccountVerifyAttempts;
  payout_accounts: PayoutAccounts;
  platforms: Platforms;
  processed_events: ProcessedEvents;
  product_key_aliases: ProductKeyAliases;
  product_refs: ProductRefs;
  push_tokens: PushTokens;
  refresh_tokens: RefreshTokens;
  risk_hits: RiskHits;
  risk_rules: RiskRules;
  sessions: Sessions;
  union_accounts: UnionAccounts;
  union_auth_sessions: UnionAuthSessions;
  union_bindings: UnionBindings;
  union_credentials: UnionCredentials;
  union_pids: UnionPids;
  user_oauth: UserOauth;
  user_risk_state: UserRiskState;
  user_tip_reads: UserTipReads;
  users: Users;
}
