/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface EventLog {
  app_id: string;
  created_at: Generated<Timestamp>;
  event_id: string;
  id: Generated<ColumnType<bigint, bigint, bigint>>;
  name: string;
  occurred_at: Timestamp;
  payload: Json;
}

export interface IdempotencyKeys {
  app_id: string;
  created_at: Generated<Timestamp>;
  expire_at: Timestamp;
  id: Generated<ColumnType<bigint, bigint, bigint>>;
  key: string;
  method: string;
  path: string;
  request_hash: string;
  response: Json | null;
  status: string;
  subject: string;
  user_id: string | null;
}

export interface ProcessedEvents {
  consumer: string;
  created_at: Generated<Timestamp>;
  event_id: string;
}

export interface DB {
  event_log: EventLog;
  idempotency_keys: IdempotencyKeys;
  processed_events: ProcessedEvents;
}
