// @couli/db: Kysely + pg access to the `app` schema (ADR-0001 §2).
// Table types come from `db.gen.ts`, generated by `pnpm db:snapshot`; never edit that file.
import { Kysely, PostgresDialect, type PostgresPool } from 'kysely';
import pg from 'pg';

import type { DB } from './db.gen.ts';
import { parseInt8, parseInt8Array } from './int8.ts';

export type { DB } from './db.gen.ts';
export {
  MONTH_PARTITIONED_TABLES,
  MONTHS_AHEAD,
  monthPartitionName,
  monthStartDate,
  monthsToEnsure,
  utcMonthStart,
} from './partitions.ts';
export type { MonthPartitionedTable } from './partitions.ts';
export { parsePgUrl, pgUrl, redactPgUrl } from './pg-url.ts';
export type { PgUrlOverrides, PgUrlParts } from './pg-url.ts';

/** Schema that holds every business table. */
export const APP_SCHEMA = 'app';

export type CreateDbOptions = {
  connectionString: string;
  /** Pool size; per-process values are listed in ADR-0001 §4.2 #11. */
  max?: number;
  applicationName?: string;
  /** Platform infrastructure can own the pool lifecycle; business modules omit this. */
  poolFactory?: (config: pg.PoolConfig) => PostgresPool;
};

const INT8_ARRAY_OID = 1016;

// int8 and int8[] are parsed as BigInt (ADR-0001 §4.2 #3). The override is scoped to pools
// created here, so libraries that own their connections (pg-boss, node-pg-migrate) keep pg's
// defaults.
function int8AsBigInt(): pg.TypeOverrides {
  const overrides = new pg.TypeOverrides();
  overrides.setTypeParser(pg.types.builtins.INT8, parseInt8);
  overrides.setTypeParser(INT8_ARRAY_OID, parseInt8Array);
  return overrides;
}

/**
 * Creates a Kysely instance bound to schema `app`, backed by its own pg pool.
 * Call `destroyDb` to close the pool.
 *
 * Platform-managed handles supply poolFactory for error handling and bounded shutdown.
 */
export function createDb(opts: CreateDbOptions): Kysely<DB> {
  const config: pg.PoolConfig = {
    connectionString: opts.connectionString,
    types: int8AsBigInt(),
  };
  if (opts.max !== undefined) {
    config.max = opts.max;
  }
  if (opts.applicationName !== undefined) {
    config.application_name = opts.applicationName;
  }
  const pool = opts.poolFactory?.(config) ?? new pg.Pool(config);
  return new Kysely<DB>({ dialect: new PostgresDialect({ pool }) }).withSchema(APP_SCHEMA);
}

/** Closes the pool behind a Kysely instance created by `createDb`. */
export async function destroyDb(db: Kysely<DB>): Promise<void> {
  await db.destroy();
}
