name: couli-load

services:
  wiremock:
    image: wiremock/wiremock:3.13.1@sha256:d61e7720f89483fdef5366843b58d1dfd06bcce5828179c9f2f54de5c28354b0
    ports:
      - '127.0.0.1:18090:8080'
    command:
      - --disable-request-journal
      - --async-response-enabled
      - 'true'
    networks:
      - load

networks:
  load:
    internal: true
