import { expect, it, vi } from 'vitest';
import { createTotpVerifier } from '../../../../apps/api/src/modules/admin/domain/totp.ts';
import { ACCOUNT, context, fixture } from './kit.ts';

// Appendix B's SHA-1 column, copied as independent expected values, not generated by the SUT.
it.each([
  [59, '94287082'],
  [1111111109, '07081804'],
  [1111111111, '14050471'],
  [1234567890, '89005924'],
  [2000000000, '69279037'],
  [20000000000, '65353130'],
] as const)('[AC-F1-06b-TOTP#1] RFC 6238 SHA-1 at %i seconds accepts %s', async (seconds, code) => {
  const f = await fixture(seconds);
  const verifier = createTotpVerifier({ ...f, digits: 8 });
  expect(await verifier.verify({ ...ACCOUNT, secretCipher: f.secretCipher, code })).toBe(true);
  expect(f.decrypt).toHaveBeenCalledWith(f.secretCipher.toString('utf8'), context(ACCOUNT));
  expect(f.consume).toHaveBeenCalledExactlyOnceWith({
    ...ACCOUNT,
    timeStep: BigInt(Math.floor(seconds / 30)),
  });
});

// RFC 4226's counters 0,1,2 are the same RFC key/HOTP primitive used at TOTP seconds 0,30,60.
it.each([
  ['previous', '755224', 0n],
  ['current', '287082', 1n],
  ['next', '359152', 2n],
] as const)(
  '[AC-F1-06b-TOTP#2] accepts %s step and claims the matched counter',
  async (_label, code, timeStep) => {
    const f = await fixture();
    const verifier = createTotpVerifier({ ...f, digits: 6 });
    expect(await verifier.verify({ ...ACCOUNT, secretCipher: f.secretCipher, code })).toBe(true);
    expect(f.consume).toHaveBeenCalledExactlyOnceWith({ ...ACCOUNT, timeStep });
  },
);

it.each([
  [59, '969429'], // counter 3 is two steps ahead
  [119, '287082'], // counter 1 is two steps behind
] as const)(
  '[AC-F1-06b-TOTP#3] rejects code %s/%s outside the one-step window',
  async (seconds, code) => {
    const f = await fixture(seconds);
    const verifier = createTotpVerifier({ ...f, digits: 6 });
    expect(await verifier.verify({ ...ACCOUNT, secretCipher: f.secretCipher, code })).toBe(false);
    expect(f.consume).not.toHaveBeenCalled();
  },
);

it.each([
  '',
  '28708',
  '0287082',
  '94287082',
  '28708a',
  '２８７０８２',
  ' 287082',
  '287082 ',
  '287082\n',
  '+287082',
  '287.82',
  '000000',
])(
  '[AC-F1-06b-TOTP#4] rejects malformed or incorrect six-digit code %j without consuming a step',
  async (code) => {
    const f = await fixture();
    const verifier = createTotpVerifier({ ...f, digits: 6 });
    expect(await verifier.verify({ ...ACCOUNT, secretCipher: f.secretCipher, code })).toBe(false);
    expect(f.consume).not.toHaveBeenCalled();
    expect(
      await verifier.verify({ ...ACCOUNT, secretCipher: f.secretCipher, code: '287082' }),
    ).toBe(true);
  },
);

it('[AC-F1-06b-TOTP#5] six-digit codes retain leading zeroes', async () => {
  const f = await fixture(1111111109);
  const verifier = createTotpVerifier({ ...f, digits: 6 });
  expect(await verifier.verify({ ...ACCOUNT, secretCipher: f.secretCipher, code: '7081804' })).toBe(
    false,
  );
  expect(await verifier.verify({ ...ACCOUNT, secretCipher: f.secretCipher, code: '081804' })).toBe(
    true,
  );
});

it('[AC-F1-06b-TOTP#6] a reused code is rejected by a new verifier sharing the replay port', async () => {
  const f = await fixture();
  const first = createTotpVerifier({ ...f, digits: 6 });
  const request = { ...ACCOUNT, secretCipher: f.secretCipher, code: '287082' };
  expect(await first.verify(request)).toBe(true);
  expect(await first.verify(request)).toBe(false);
  const second = createTotpVerifier({ ...f, digits: 6 });
  expect(await second.verify(request)).toBe(false);
});

it('[AC-F1-06b-TOTP#7] moving the server clock cannot revive an already accepted future code', async () => {
  const f = await fixture();
  const verifier = createTotpVerifier({ ...f, digits: 6 });
  const request = { ...ACCOUNT, secretCipher: f.secretCipher, code: '359152' };
  expect(await verifier.verify(request)).toBe(true);
  f.clock.advanceMs(30_000);
  expect(await verifier.verify(request)).toBe(false);
  f.clock.advanceMs(30_000);
  expect(await verifier.verify(request)).toBe(false);
  expect(f.consume.mock.calls.every(([claim]) => claim.timeStep === 2n)).toBe(true);
});

it('[AC-F1-06b-TOTP#8] reads Clock at each call and closes the window exactly at the boundary', async () => {
  const f = await fixture(89.999);
  const verifier = createTotpVerifier({ ...f, digits: 6 });
  const other = { ...ACCOUNT, adminId: '019a0000-0000-7000-8000-000000000002' };
  expect(await verifier.verify({ ...ACCOUNT, secretCipher: f.secretCipher, code: '287082' })).toBe(
    true,
  );
  f.clock.advanceMs(1);
  expect(
    await verifier.verify({ ...other, secretCipher: f.encryptFor(other), code: '287082' }),
  ).toBe(false);
  expect(
    await verifier.verify({ ...other, secretCipher: f.encryptFor(other), code: '969429' }),
  ).toBe(true);
});

it('[AC-F1-06b-TOTP#9] simultaneous attempts on shared storage admit exactly one', async () => {
  const f = await fixture();
  const first = createTotpVerifier({ ...f, digits: 6 });
  const second = createTotpVerifier({ ...f, digits: 6 });
  const request = { ...ACCOUNT, secretCipher: f.secretCipher, code: '287082' };
  const results = await Promise.all([first.verify(request), second.verify(request)]);
  expect(results.filter(Boolean)).toHaveLength(1);
  expect(results.filter((value) => value === false)).toHaveLength(1);
});

it('[AC-F1-06b-TOTP#10] replay keys distinguish app_id and admin_id', async () => {
  const f = await fixture();
  const verifier = createTotpVerifier({ ...f, digits: 6 });
  for (const account of [
    ACCOUNT,
    { ...ACCOUNT, appId: 'couli_two' },
    { ...ACCOUNT, adminId: '019a0000-0000-7000-8000-000000000003' },
  ]) {
    const request = { ...account, secretCipher: f.encryptFor(account), code: '287082' };
    expect(await verifier.verify(request)).toBe(true);
    expect(await verifier.verify(request)).toBe(false);
  }
});

it('[AC-F1-06b-TOTP#11] replay-store refusal or failure cannot authenticate', async () => {
  const f = await fixture();
  const consume = vi
    .fn()
    .mockResolvedValueOnce(false)
    .mockRejectedValueOnce(new Error('store unavailable'));
  const verifier = createTotpVerifier({ ...f, replay: { consume }, digits: 6 });
  const request = { ...ACCOUNT, secretCipher: f.secretCipher, code: '287082' };
  expect(await verifier.verify(request)).toBe(false);
  expect(await verifier.verify(request).catch(() => false)).toBe(false);
});

it('[AC-F1-06b-TOTP#12] ciphertext encrypted for another account cannot authenticate or consume', async () => {
  const f = await fixture();
  const verifier = createTotpVerifier({ ...f, digits: 6 });
  const other = { ...ACCOUNT, adminId: '019a0000-0000-7000-8000-000000000004' };
  expect(
    await verifier
      .verify({ ...other, secretCipher: f.secretCipher, code: '287082' })
      .catch(() => false),
  ).toBe(false);
  expect(f.consume).not.toHaveBeenCalled();
});
