// GENERATED FILE. Do not edit by hand.
// Source: contracts/error-codes.yaml
// Regenerate: pnpm contracts:codegen (drift is checked by pnpm contracts:check)

/**
 * Error code catalog (规划/08 §13.11 is the single allocation table; data shapes from 规划/04 §7).
 * Clients act on `code`; texts come from the dictionary key error.<code> (BR-TEXT-14).
 */
export const errorCodes = {
  10001: {
    http: 401,
    meaning: "未登录",
    action: "跳 Login，成功后恢复 pending_action",
    retry: "登录后",
    retry_kind: "after_action",
    data: {},
    headers: [],
    sources: ["BR-ID-01","BR-ID-10","BR-AI-11","BR-AI-23","BR-ATTR-05"],
    phase: null,
    deprecated: false,
  },
  10002: {
    http: 401,
    meaning: "access_token 过期",
    action: "单飞刷新后重放原请求 1 次；刷新失败清会话跳登录",
    retry: "刷新后",
    retry_kind: "after_action",
    data: {},
    headers: [],
    sources: ["BR-ID-01","BR-ID-07"],
    phase: null,
    deprecated: false,
  },
  10003: {
    http: 403,
    meaning: "需要二次验证（含 step_up_token 过期）",
    action: "弹短信验证，拿到 step_up_token 后重放",
    retry: "验证后",
    retry_kind: "after_action",
    data: {},
    headers: [],
    sources: ["BR-ID-08","BR-WDR-01","BR-WDR-03"],
    phase: null,
    deprecated: false,
  },
  10004: {
    http: 403,
    meaning: "需要同意（协议重新同意、AI 单独同意、实名授权、劳务协议等）",
    action: "弹对应同意组件，同意后重放",
    retry: "同意后",
    retry_kind: "after_action",
    data: {"consent_type":["privacy","agreement","ai_third_party","id_verification","personalization","labor_agreement"]},
    headers: [],
    sources: ["BR-ID-11","BR-ID-12","BR-ID-14","BR-AI-13","BR-INV-05"],
    phase: null,
    deprecated: false,
  },
  10005: {
    http: 403,
    meaning: "需要绑定手机号",
    action: "跳 BindPhone，完成后恢复 pending_action",
    retry: "绑定后",
    retry_kind: "after_action",
    data: {},
    headers: [],
    sources: ["BR-ID-01","BR-ID-03","BR-AI-11","BR-INV-02"],
    phase: null,
    deprecated: false,
  },
  10006: {
    http: 403,
    meaning: "账号已冻结或封禁",
    action: "展示封禁说明页与申诉入口",
    retry: "否",
    retry_kind: "never",
    data: {},
    headers: [],
    sources: ["BR-ID-31","BR-WDR-03"],
    phase: null,
    deprecated: false,
  },
  10007: {
    http: 403,
    meaning: "账号在注销冷静期或处理中",
    action: "冷静期跳注销进度页（可撤回）；processing 仅提示",
    retry: "否",
    retry_kind: "never",
    data: {"stage":["cooling","processing"]},
    headers: [],
    sources: ["BR-ID-27"],
    phase: null,
    deprecated: false,
  },
  10401: {
    http: 401,
    meaning: "请求签名无效或重放（X-Nonce 重复 / 时间戳超窗）",
    action: "不自动重放，上报埋点",
    retry: "否",
    retry_kind: "never",
    data: {},
    headers: [],
    sources: ["BR-ID-01","BR-ID-05","BR-ID-09"],
    phase: null,
    deprecated: false,
  },
  10402: {
    http: 401,
    meaning: "设备未注册、已失效或非服务端签发",
    action: "重新注册设备后重放 1 次",
    retry: "重新注册后",
    retry_kind: "after_action",
    data: {},
    headers: [],
    sources: ["BR-ID-01","BR-ID-05","BR-ID-09"],
    phase: null,
    deprecated: false,
  },
  10403: {
    http: 403,
    meaning: "App 或请求来源不被允许（含令牌作用域越权）",
    action: "不跳登录，仅提示",
    retry: "否",
    retry_kind: "never",
    data: {},
    headers: [],
    sources: ["BR-ID-01","BR-ID-07","BR-ID-32"],
    phase: null,
    deprecated: false,
  },
  10404: {
    http: 401,
    meaning: "refresh_token 失效，需重新登录",
    action: "清会话，跳 Login",
    retry: "—",
    retry_kind: "not_applicable",
    data: {},
    headers: [],
    sources: ["BR-ID-07"],
    phase: null,
    deprecated: false,
  },
  20001: {
    http: 400,
    meaning: "参数校验失败",
    action: "在对应字段旁提示（带 reason 取子键文案）",
    retry: "否",
    retry_kind: "never",
    data: {"fields":null,"reason":["watch_target_invalid","nickname_sensitive"]},
    headers: [],
    sources: ["BR-ID-25","BR-ID-39","BR-AI-23","BR-TEXT-13","BR-WDR-03","BR-WATCH-04"],
    phase: null,
    deprecated: false,
  },
  20002: {
    http: 400,
    meaning: "验证码错误",
    action: "提示重新输入",
    retry: "否",
    retry_kind: "never",
    data: {},
    headers: [],
    sources: ["BR-ID-05"],
    phase: null,
    deprecated: false,
  },
  20003: {
    http: 400,
    meaning: "验证码已过期或已作废（含错满 5 次）",
    action: "提示重新获取验证码",
    retry: "否",
    retry_kind: "never",
    data: {},
    headers: [],
    sources: ["BR-ID-05"],
    phase: null,
    deprecated: false,
  },
  20901: {
    http: 409,
    meaning: "幂等键冲突（同键不同请求体）",
    action: "不重放；生成新幂等键后由用户重新提交",
    retry: "否",
    retry_kind: "never",
    data: {},
    headers: [],
    sources: ["BR-ID-01","BR-WDR-03","BR-WDR-07"],
    phase: null,
    deprecated: false,
  },
  20902: {
    http: 409,
    meaning: "状态已变化（并发修改冲突）",
    action: "刷新详情",
    retry: "刷新后",
    retry_kind: "after_action",
    data: {"resource":["order","order_attribution","withdrawal","settle_batch","ticket"]},
    headers: [],
    sources: ["BR-FUND-01","BR-FUND-04","BR-ATTR-20","BR-WDR-08","BR-ID-36"],
    phase: null,
    deprecated: false,
  },
  30101: {
    http: 422,
    meaning: "淘宝未授权 / 未备案；站长授权过期或失效期间带 reason=auth_unavailable，不带 auth_url",
    action: "弹 AuthSheet → 拉起授权 → 自动重放；auth_unavailable 不拉起授权、不外跳、只提示，不提供无返利购买",
    retry: "授权后；auth_unavailable：稍后",
    retry_kind: "after_action",
    data: {"auth_url":null,"state":null,"reason":["auth_unavailable"]},
    headers: [],
    sources: ["BR-ID-17","BR-ID-18","BR-ID-24","BR-ATTR-05","BR-TEXT-14"],
    phase: null,
    deprecated: false,
  },
  30102: {
    http: 422,
    meaning: "淘宝授权已失效，需重新授权；站长授权过期或失效期间带 reason=auth_unavailable",
    action: "同 30101",
    retry: "同 30101",
    retry_kind: "after_action",
    data: {"reason":["auth_unavailable"]},
    headers: [],
    sources: ["BR-ID-17","BR-ID-21","BR-ID-24","BR-TEXT-14"],
    phase: null,
    deprecated: false,
  },
  30103: {
    http: 422,
    meaning: "该渠道已被限制推广（渠道 ID 黑名单）",
    action: "给无返利购买与联系客服两个按钮",
    retry: "否",
    retry_kind: "never",
    data: {},
    headers: [],
    sources: ["规划/04 §7"],
    phase: null,
    deprecated: false,
  },
  30104: {
    http: 422,
    meaning: "淘宝授权请求已过期或已使用（state 超 10 分钟或重复提交）",
    action: "重新获取 auth_url 后重新发起授权",
    retry: "重新授权后",
    retry_kind: "after_action",
    data: {},
    headers: [],
    sources: ["BR-ID-17"],
    phase: null,
    deprecated: false,
  },
  30111: {
    http: 422,
    meaning: "拼多多未授权",
    action: "同 30101",
    retry: "授权后",
    retry_kind: "after_action",
    data: {},
    headers: [],
    sources: ["BR-ID-18","BR-ID-22","BR-TEXT-14"],
    phase: null,
    deprecated: false,
  },
  30121: {
    http: 422,
    meaning: "京东该链接暂不支持转链（权限不足）",
    action: "给无返利购买按钮（BR-PRICE-08）",
    retry: "否",
    retry_kind: "never",
    data: {},
    headers: [],
    sources: ["BR-PRICE-08"],
    phase: null,
    deprecated: false,
  },
  30131: {
    http: 422,
    meaning: "不支持该链接或平台",
    action: "仅提示",
    retry: "否",
    retry_kind: "never",
    data: {},
    headers: [],
    sources: ["BR-PROD-03","BR-PROD-10","BR-TEXT-14"],
    phase: null,
    deprecated: false,
  },
  30132: {
    http: 422,
    meaning: "口令无法识别（含口令解析权限未开通）",
    action: "给商品名搜索按钮（预填规则见 BR-TEXT-14 error.30132）",
    retry: "否",
    retry_kind: "never",
    data: {},
    headers: [],
    sources: ["BR-PROD-03","BR-TEXT-14"],
    phase: null,
    deprecated: false,
  },
  30141: {
    http: 422,
    meaning: "商品已下架",
    action: "不外跳，卡片置灰（availability=off_shelf）；Agent 场景追加换一批入口",
    retry: "否",
    retry_kind: "never",
    data: {},
    headers: [],
    sources: ["BR-PRICE-14","BR-PROD-05","BR-TEXT-14"],
    phase: null,
    deprecated: false,
  },
  30142: {
    http: 422,
    meaning: "废弃（原义：券已失效或领完），服务端不再返回",
    action: "按表外 3xxxx 处理",
    retry: "—",
    retry_kind: "not_applicable",
    data: {},
    headers: [],
    sources: ["BR-PRICE-14"],
    phase: null,
    deprecated: true,
  },
  30143: {
    http: 422,
    meaning: "商品信息已失效（ref_expired，检索不到同键商品或派生出不同的键）",
    action: "跳搜索（BR-PROD-05）",
    retry: "否",
    retry_kind: "never",
    data: {},
    headers: [],
    sources: ["BR-PROD-03","BR-PROD-05","BR-PROD-06"],
    phase: null,
    deprecated: false,
  },
  30144: {
    http: 404,
    meaning: "购买链接不存在（link_id 不存在或不属于本 App）",
    action: "按卡片 product_key + item_ref 自动重新请求转链，替换卡片后仍须用户再次点击",
    retry: "重新转链后",
    retry_kind: "after_action",
    data: {},
    headers: [],
    sources: ["BR-ATTR-05"],
    phase: null,
    deprecated: false,
  },
  30151: {
    http: 422,
    meaning: "该淘宝账号已绑定本 App 其他用户",
    action: "给无返利购买与联系客服两个按钮，不透露对方账号",
    retry: "否",
    retry_kind: "never",
    data: {},
    headers: [],
    sources: ["BR-ID-18","BR-ID-19","BR-ATTR-07"],
    phase: null,
    deprecated: false,
  },
  30152: {
    http: 422,
    meaning: "废弃（原义：换绑间隔不足），服务端不再返回",
    action: "按表外 3xxxx 处理",
    retry: "—",
    retry_kind: "not_applicable",
    data: {},
    headers: [],
    sources: ["BR-ID-19"],
    phase: null,
    deprecated: true,
  },
  30153: {
    http: 422,
    meaning: "该平台返利已被停用（绑定为 blocked 且用户未被封禁）",
    action: "给无返利购买与联系客服两个按钮",
    retry: "否",
    retry_kind: "never",
    data: {},
    headers: [],
    sources: ["BR-ID-17","BR-ID-18"],
    phase: null,
    deprecated: false,
  },
  30201: {
    http: 404,
    meaning: "订单不存在",
    action: "仅提示",
    retry: "否",
    retry_kind: "never",
    data: {},
    headers: [],
    sources: ["BR-ATTR-17","BR-ATTR-19"],
    phase: null,
    deprecated: false,
  },
  30202: {
    http: 422,
    meaning: "订单不可找回",
    action: "按 data.reason 提示",
    retry: "否",
    retry_kind: "never",
    data: {"reason":["FACTOR_MISMATCH","CLAIM_EXPIRED","ORDER_INVALID","ALREADY_YOURS"]},
    headers: [],
    sources: ["BR-ATTR-17","BR-ATTR-19"],
    phase: null,
    deprecated: false,
  },
  30203: {
    http: 422,
    meaning: "今日找回次数已用完（风控禁止时 reason=RISK_BLOCKED）",
    action: "仅提示",
    retry: "次日",
    retry_kind: "later",
    data: {"reason":["RISK_BLOCKED"]},
    headers: [],
    sources: ["BR-ATTR-17","BR-ATTR-19"],
    phase: null,
    deprecated: false,
  },
  30204: {
    http: 422,
    meaning: "订单已被认领（含已锁定）",
    action: "仅提示，不透露对方信息",
    retry: "否",
    retry_kind: "never",
    data: {},
    headers: [],
    sources: ["BR-ATTR-12","BR-ATTR-17","BR-ATTR-20"],
    phase: null,
    deprecated: false,
  },
  30205: {
    http: 422,
    meaning: "已提交过该订单的找回",
    action: "跳找回记录",
    retry: "否",
    retry_kind: "never",
    data: {},
    headers: [],
    sources: ["BR-ATTR-17"],
    phase: null,
    deprecated: false,
  },
  30206: {
    http: 422,
    meaning: "找回功能暂时关闭（claims.enabled=off）",
    action: "找回入口置灰",
    retry: "稍后",
    retry_kind: "later",
    data: {},
    headers: [],
    sources: ["BR-ATTR-17"],
    phase: null,
    deprecated: false,
  },
  30301: {
    http: 422,
    meaning: "余额不足",
    action: "仅提示",
    retry: "否",
    retry_kind: "never",
    data: {},
    headers: [],
    sources: ["BR-WDR-03"],
    phase: null,
    deprecated: false,
  },
  30302: {
    http: 422,
    meaning: "余额为负，暂不能提现",
    action: "展示负余额说明",
    retry: "否",
    retry_kind: "never",
    data: {},
    headers: [],
    sources: ["BR-FUND-10","BR-FUND-11","BR-WDR-03","BR-WDR-05"],
    phase: null,
    deprecated: false,
  },
  30303: {
    http: 422,
    meaning: "不满足提现条件（data.reason 取值见来源条目，含 account_frozen）",
    action: "按 data.reason 提示",
    retry: "否",
    retry_kind: "never",
    data: {"reason":null},
    headers: [],
    sources: ["BR-WDR-02","BR-WDR-03","BR-WDR-04","BR-WDR-05","BR-FUND-19"],
    phase: null,
    deprecated: false,
  },
  30304: {
    http: 422,
    meaning: "未实名",
    action: "跳 RealName",
    retry: "实名后",
    retry_kind: "after_action",
    data: {},
    headers: [],
    sources: ["BR-ID-01","BR-WDR-03"],
    phase: null,
    deprecated: false,
  },
  30305: {
    http: 422,
    meaning: "未绑定收款账号",
    action: "跳 PayoutAccount",
    retry: "绑定后",
    retry_kind: "after_action",
    data: {},
    headers: [],
    sources: ["BR-WDR-03"],
    phase: null,
    deprecated: false,
  },
  30306: {
    http: 422,
    meaning: "提现暂停（withdraw.enabled 关闭）",
    action: "提现按钮置灰",
    retry: "否",
    retry_kind: "never",
    data: {},
    headers: [],
    sources: ["BR-WDR-03","BR-WDR-17"],
    phase: null,
    deprecated: false,
  },
  30307: {
    http: 422,
    meaning: "收款账号姓名与实名不一致",
    action: "跳 PayoutAccount",
    retry: "否",
    retry_kind: "never",
    data: {},
    headers: [],
    sources: ["BR-WDR-02","BR-WDR-03"],
    phase: null,
    deprecated: false,
  },
  30308: {
    http: 422,
    meaning: "收款账号已被其他实名绑定",
    action: "跳 PayoutAccount，不透露对方信息",
    retry: "否",
    retry_kind: "never",
    data: {},
    headers: [],
    sources: ["BR-WDR-02"],
    phase: null,
    deprecated: false,
  },
  30309: {
    http: 422,
    meaning: "未成年人提现限制",
    action: "展示未成年提现规则",
    retry: "否",
    retry_kind: "never",
    data: {},
    headers: [],
    sources: ["BR-WDR-06","BR-ID-26"],
    phase: null,
    deprecated: false,
  },
  30401: {
    http: 422,
    meaning: "邀请码无效（含格式错误、邀请人不存在或不可用、邀请人未满 18 周岁，不透露原因）",
    action: "仅提示",
    retry: "否",
    retry_kind: "never",
    data: {},
    headers: [],
    sources: ["BR-INV-02","BR-INV-19","BR-ID-26"],
    phase: null,
    deprecated: false,
  },
  30402: {
    http: 422,
    meaning: "已绑定上级 / 已用过绑定机会",
    action: "仅提示",
    retry: "否",
    retry_kind: "never",
    data: {},
    headers: [],
    sources: ["BR-INV-02","BR-INV-03"],
    phase: null,
    deprecated: false,
  },
  30403: {
    http: 422,
    meaning: "不能绑定该邀请人（自己、下级、同设备）",
    action: "仅提示",
    retry: "否",
    retry_kind: "never",
    data: {},
    headers: [],
    sources: ["BR-INV-08"],
    phase: null,
    deprecated: false,
  },
  30404: {
    http: 422,
    meaning: "已超过补填期限",
    action: "仅提示",
    retry: "否",
    retry_kind: "never",
    data: {},
    headers: [],
    sources: ["BR-INV-07"],
    phase: null,
    deprecated: false,
  },
  30405: {
    http: 422,
    meaning: "该身份证已被其他账号实名",
    action: "不透露对方账号",
    retry: "否",
    retry_kind: "never",
    data: {},
    headers: [],
    sources: ["BR-ID-25"],
    phase: null,
    deprecated: false,
  },
  30406: {
    http: 422,
    meaning: "实名核验不通过",
    action: "仅提示",
    retry: "否",
    retry_kind: "never",
    data: {},
    headers: [],
    sources: ["BR-ID-25"],
    phase: null,
    deprecated: false,
  },
  30407: {
    http: 422,
    meaning: "年龄不满足要求（未满 14 周岁不予实名）",
    action: "仅提示",
    retry: "否",
    retry_kind: "never",
    data: {},
    headers: [],
    sources: ["BR-ID-25","BR-ID-26"],
    phase: null,
    deprecated: false,
  },
  30408: {
    http: 422,
    meaning: "邀请绑定暂停（growth.invite_bind.enabled=off）",
    action: "落地页引导直接下载注册",
    retry: "稍后",
    retry_kind: "later",
    data: {},
    headers: [],
    sources: ["BR-INV-02","BR-INV-05","BR-INV-06","BR-INV-21"],
    phase: null,
    deprecated: false,
  },
  30409: {
    http: 422,
    meaning: "已有订单、找回申请或下级，不能补填或改上级",
    action: "仅提示",
    retry: "否",
    retry_kind: "never",
    data: {},
    headers: [],
    sources: ["BR-INV-02","BR-INV-07","BR-INV-10"],
    phase: null,
    deprecated: false,
  },
  30410: {
    http: 422,
    meaning: "今日实名次数已用完",
    action: "仅提示，不暴露身份证是否已被占用",
    retry: "次日",
    retry_kind: "later",
    data: {},
    headers: [],
    sources: ["BR-ID-25"],
    phase: null,
    deprecated: false,
  },
  30411: {
    http: 422,
    meaning: "目标手机号已属于本 App 其他账号；满足并号条件时带 reason=mergeable 与 merge_ticket",
    action: "无 reason 仅提示；mergeable 弹并入确认，凭 merge_ticket 调 POST /v1/auth/merge",
    retry: "否",
    retry_kind: "never",
    data: {"reason":["mergeable"],"merge_ticket":null},
    headers: [],
    sources: ["BR-ID-06"],
    phase: null,
    deprecated: false,
  },
  30412: {
    http: 422,
    meaning: "有进行中的提现（PENDING_REVIEW / APPROVED / PAYING），暂不能申请注销",
    action: "仅提示",
    retry: "提现完结后",
    retry_kind: "later",
    data: {},
    headers: [],
    sources: ["BR-ID-27","BR-ID-31"],
    phase: null,
    deprecated: false,
  },
  30413: {
    http: 422,
    meaning: "未满 18 周岁，不开放邀请与分享",
    action: "隐藏邀请与分享赚入口",
    retry: "否",
    retry_kind: "never",
    data: {"reason":["self_minor"]},
    headers: [],
    sources: ["BR-ID-26","BR-INV-18","BR-INV-19"],
    phase: null,
    deprecated: false,
  },
  30414: {
    http: 422,
    meaning: "暂不支持自助更换手机号（account.phone_change_enabled=false，不含首次绑定）",
    action: "仅提示",
    retry: "否",
    retry_kind: "never",
    data: {},
    headers: [],
    sources: ["BR-ID-06"],
    phase: null,
    deprecated: false,
  },
  30415: {
    http: 422,
    meaning: "昵称当月修改次数已满",
    action: "仅提示",
    retry: "次月",
    retry_kind: "later",
    data: {},
    headers: [],
    sources: ["BR-ID-39"],
    phase: null,
    deprecated: false,
  },
  30416: {
    http: 422,
    meaning: "账户有待扣回金额（余额为负），暂不能注销",
    action: "注销页展示提示与联系客服，不进入冷静期",
    retry: "余额回正后",
    retry_kind: "later",
    data: {"amount_fen":null},
    headers: [],
    sources: ["BR-ID-27","BR-FUND-10"],
    phase: null,
    deprecated: false,
  },
  30501: {
    http: 422,
    meaning: "AI 助手未开放",
    action: "隐藏或置灰入口",
    retry: "否",
    retry_kind: "never",
    data: {},
    headers: [],
    sources: ["BR-AI-12","BR-AI-23","BR-ID-03"],
    phase: null,
    deprecated: false,
  },
  30502: {
    http: 422,
    meaning: "今日 AI 次数已用完",
    action: "跳搜索",
    retry: "次日",
    retry_kind: "later",
    data: {},
    headers: [],
    sources: ["BR-AI-15","BR-AI-23","BR-ID-03"],
    phase: null,
    deprecated: false,
  },
  30503: {
    http: 422,
    meaning: "内容不支持",
    action: "仅提示",
    retry: "否",
    retry_kind: "never",
    data: {},
    headers: [],
    sources: ["BR-ID-03"],
    phase: null,
    deprecated: false,
  },
  30504: {
    http: 422,
    meaning: "会话已过期、达轮数上限或不可访问",
    action: "新建会话",
    retry: "新建会话后",
    retry_kind: "after_action",
    data: {"reason":null},
    headers: [],
    sources: ["BR-AI-15","BR-AI-20","BR-AI-23"],
    phase: null,
    deprecated: false,
  },
  30505: {
    http: 404,
    meaning: "run 不存在或已结束",
    action: "刷新会话消息",
    retry: "否",
    retry_kind: "never",
    data: {},
    headers: [],
    sources: ["BR-AI-23"],
    phase: null,
    deprecated: false,
  },
  30506: {
    http: 409,
    meaning: "本会话有进行中的 run（run_in_progress）",
    action: "发送按钮保持禁用，当前 run 结束后可再发",
    retry: "run 结束后",
    retry_kind: "later",
    data: {},
    headers: [],
    sources: ["BR-AI-23"],
    phase: null,
    deprecated: false,
  },
  30601: {
    http: 422,
    meaning: "已领取过该淘礼金",
    action: "仅提示",
    retry: "否",
    retry_kind: "never",
    data: {},
    headers: [],
    sources: ["规划/04 §7"],
    phase: null,
    deprecated: false,
  },
  30602: {
    http: 422,
    meaning: "淘礼金已抢光（含点击时领完）",
    action: "淘礼金按钮置灰，给普通购买入口",
    retry: "否",
    retry_kind: "never",
    data: {},
    headers: [],
    sources: ["BR-PRICE-14"],
    phase: null,
    deprecated: false,
  },
  30603: {
    http: 422,
    meaning: "活动未开始或已结束",
    action: "仅提示",
    retry: "否",
    retry_kind: "never",
    data: {},
    headers: [],
    sources: ["规划/04 §7"],
    phase: null,
    deprecated: false,
  },
  30604: {
    http: 422,
    meaning: "不满足领取条件",
    action: "仅提示",
    retry: "否",
    retry_kind: "never",
    data: {},
    headers: [],
    sources: ["规划/04 §7"],
    phase: null,
    deprecated: false,
  },
  30701: {
    http: 404,
    meaning: "页面或内容不存在",
    action: "显示空态",
    retry: "否",
    retry_kind: "never",
    data: {},
    headers: [],
    sources: ["规划/04 §7"],
    phase: null,
    deprecated: false,
  },
  30801: {
    http: 422,
    meaning: "当前已达到目标价",
    action: "仅提示",
    retry: "否",
    retry_kind: "never",
    data: {"reason":["watch_target_already_met"]},
    headers: [],
    sources: ["BR-WATCH-04"],
    phase: "P1",
    deprecated: false,
  },
  30802: {
    http: 422,
    meaning: "提醒数量已达上限",
    action: "列表显示已设数量，引导删除旧提醒",
    retry: "删除旧提醒或到期后",
    retry_kind: "after_action",
    data: {"reason":["watch_limit_exceeded"]},
    headers: [],
    sources: ["BR-WATCH-17"],
    phase: "P1",
    deprecated: false,
  },
  30803: {
    http: 409,
    meaning: "同商品已有提醒",
    action: "跳到已有提醒（修改目标价）",
    retry: "否",
    retry_kind: "never",
    data: {"reason":["watch_duplicate"],"watch_id":null},
    headers: [],
    sources: ["BR-WATCH-02"],
    phase: "P1",
    deprecated: false,
  },
  30804: {
    http: 409,
    meaning: "同商品有可续期的过期提醒",
    action: "跳到已有提醒（续期）",
    retry: "否",
    retry_kind: "never",
    data: {"reason":["watch_expired_renewable"],"watch_id":null},
    headers: [],
    sources: ["BR-WATCH-02","BR-WATCH-10"],
    phase: "P1",
    deprecated: false,
  },
  30805: {
    http: 422,
    meaning: "暂时无法获取价格（不建 watch 行）",
    action: "仅提示，不建提醒",
    retry: "稍后",
    retry_kind: "later",
    data: {"reason":["watch_quote_unavailable"]},
    headers: [],
    sources: ["BR-WATCH-07","BR-WATCH-10"],
    phase: "P1",
    deprecated: false,
  },
  30806: {
    http: 422,
    meaning: "该平台提醒暂停服务",
    action: "仅提示",
    retry: "否",
    retry_kind: "never",
    data: {"reason":["watch_platform_disabled"]},
    headers: [],
    sources: ["BR-WATCH-27"],
    phase: "P1",
    deprecated: false,
  },
  40901: {
    http: 409,
    meaning: "同一请求正在处理",
    action: "保持加载态，稍后查询结果",
    retry: "稍后",
    retry_kind: "later",
    data: {},
    headers: [],
    sources: ["BR-ID-01","BR-ID-08","BR-WDR-03","BR-WDR-07"],
    phase: null,
    deprecated: false,
  },
  42901: {
    http: 429,
    meaning: "请求过于频繁",
    action: "按 Retry-After 禁用按钮，缺省 5 秒",
    retry: "稍后",
    retry_kind: "later",
    data: {},
    headers: ["Retry-After"],
    sources: ["BR-TEXT-14","BR-ID-05","BR-INV-02","BR-AI-23"],
    phase: null,
    deprecated: false,
  },
  44001: {
    http: 403,
    meaning: "风控拦截（号段或手机号黑名单、设备或 IP 注册上限、封禁用户的受限操作）",
    action: "给申诉入口；文案取字典 risk_msg.<code>",
    retry: "否",
    retry_kind: "never",
    data: {"risk_msg_code":null},
    headers: [],
    sources: ["BR-TEXT-14","BR-ID-05","BR-ID-06","BR-ID-31","BR-ID-32"],
    phase: null,
    deprecated: false,
  },
  44002: {
    http: 403,
    meaning: "设备环境异常",
    action: "仅提示",
    retry: "否",
    retry_kind: "never",
    data: {},
    headers: [],
    sources: ["BR-ID-01"],
    phase: null,
    deprecated: false,
  },
  44003: {
    http: 403,
    meaning: "需要人机验证（是否启用待决策，08 §13.3）",
    action: "拉起人机验证组件，通过后带验证凭证重放",
    retry: "验证后",
    retry_kind: "after_action",
    data: {},
    headers: [],
    sources: ["BR-ID-05","BR-ID-32"],
    phase: null,
    deprecated: false,
  },
  50001: {
    http: 500,
    meaning: "服务端错误",
    action: "通用错误态 + trace_id 后 6 位",
    retry: "是",
    retry_kind: "immediate",
    data: {},
    headers: [],
    sources: ["BR-TEXT-14","BR-INV-06"],
    phase: null,
    deprecated: false,
  },
  50301: {
    http: 503,
    meaning: "平台维护或熔断，或平台未开放",
    action: "maintenance 弹 Toast、购买按钮禁用；not_launched 购买按钮禁用、不弹 Toast；无 reason 按 maintenance",
    retry: "maintenance：稍后；not_launched：否",
    retry_kind: "later",
    data: {"platform":null,"reason":["maintenance","not_launched"]},
    headers: [],
    sources: ["BR-TEXT-14","BR-PRICE-13","BR-PROD-05","BR-PROD-10"],
    phase: null,
    deprecated: false,
  },
  50302: {
    http: 503,
    meaning: "AI 暂不可用（只在服务端按关键词无模型出卡也失败时返回）",
    action: "跳搜索",
    retry: "稍后",
    retry_kind: "later",
    data: {"fallback":null},
    headers: [],
    sources: ["BR-TEXT-14","BR-AI-14"],
    phase: null,
    deprecated: false,
  },
  50303: {
    http: 503,
    meaning: "暂时无法确认价格或生成链接（点击复核失败且无缓存，或取价成功但转链失败）",
    action: "不外跳返利链接；给重试主按钮与无返利购买次按钮（BR-PRICE-08）",
    retry: "稍后",
    retry_kind: "later",
    data: {},
    headers: [],
    sources: ["BR-PRICE-08","BR-PRICE-13"],
    phase: null,
    deprecated: false,
  },
  50304: {
    http: 503,
    meaning: "某平台搜索暂不可用（联盟超时、限流或熔断且无可用搜索缓存）",
    action: "搜索页显示空态与重试按钮；Agent 改查其他平台",
    retry: "稍后",
    retry_kind: "later",
    data: {"platform":null},
    headers: [],
    sources: ["BR-PROD-07","BR-PRICE-11","BR-TEXT-14"],
    phase: null,
    deprecated: false,
  },
  50401: {
    http: 504,
    meaning: "依赖超时",
    action: "通用错误态 + trace_id 后 6 位",
    retry: "是",
    retry_kind: "immediate",
    data: {},
    headers: [],
    sources: ["BR-PROD-05","BR-ID-25"],
    phase: null,
    deprecated: false,
  },
} as const;
export type ErrorCode = keyof typeof errorCodes;
export type ErrorRetryKind = (typeof errorCodes)[ErrorCode]["retry_kind"];

/** Code ranges reserved as a whole (e.g. the JSBridge-only 90001–90500). */
export const errorCodeRanges = [{"from":90001,"to":90500,"meaning":"JSBridge 专用码段"}] as const;
