// Self-consistency of specs/external-navigation.vectors.json (08 BR-ATTR-29 ② and 细则; 03 §5.1):
// an independent reading of the policy, written here with the WHATWG URL parser, must reach the
// expected outcome of every vector. The vectors were generated by another implementation; this
// test keeps the two in agreement and the file well-formed. The apps implement the policy
// themselves and run the same vectors.
import { readFileSync } from 'node:fs';
import { expect, it } from 'vitest';

type Rule = { platform: string; category: string; hosts: string[]; path_patterns: string[] };
type Table = { version: string; rules: Rule[] };
type TableName = 'current' | 'last_good' | 'bundled';
type Switches = { union_host_block: boolean | null; product_intercept: boolean };
type Outcome = {
  action: string;
  notice: string | null;
  parse_url: string | null;
  table_used: TableName;
};
type NavCase = {
  note: string;
  url: string;
  frame: 'initial' | 'main' | 'subframe' | 'new_window';
  switches: Switches;
  basic_mode: boolean;
  download: boolean;
  tables: TableName[];
  expected: Outcome;
};
type BrowserCase = {
  note: string;
  url: string;
  tables: TableName[];
  expected: { can_open_in_browser: boolean; table_used: TableName };
};
type Vectors = {
  rule_tables: Record<TableName, Table>;
  navigation_cases: NavCase[];
  open_in_browser_cases: BrowserCase[];
};

const vectors = JSON.parse(
  readFileSync(new URL('../../../specs/external-navigation.vectors.json', import.meta.url), 'utf8'),
) as Vectors;

function tableFor(names: TableName[]): { name: TableName; table: Table } {
  const name = (['current', 'last_good', 'bundled'] as const).find((n) => names.includes(n));
  if (name === undefined) throw new Error('a case without any rule table');
  return { name, table: vectors.rule_tables[name] };
}

/** Decodes valid %XX once (as UTF-8); any other % stays literal. */
function decodeOnce(path: string): string {
  const raw = Buffer.from(path, 'utf8');
  const bytes: number[] = [];
  for (let i = 0; i < raw.length; i++) {
    const hex = raw.subarray(i + 1, i + 3).toString('latin1');
    if (raw[i] === 0x25 && /^[0-9a-fA-F]{2}$/.test(hex)) {
      bytes.push(parseInt(hex, 16));
      i += 2;
    } else bytes.push(raw[i] ?? 0);
  }
  return Buffer.from(bytes).toString('utf8');
}

/** Host and decoded path of a well-formed https URL, or null (fail closed). */
function normalise(raw: string): { host: string; path: string } | null {
  let url: URL;
  try {
    url = new URL(raw);
  } catch {
    return null;
  }
  if (url.protocol !== 'https:' || url.username !== '' || url.password !== '') return null;
  const host = url.hostname.replace(/\.$/, '').toLowerCase();
  return host === '' ? null : { host, path: decodeOnce(url.pathname) };
}

function globToRegExp(pattern: string): RegExp {
  let source = '';
  for (let i = 0; i < pattern.length; i++) {
    if (pattern.startsWith('**', i)) {
      source += '[\\s\\S]*';
      i++;
    } else if (pattern[i] === '*') source += '[^/]*';
    else source += (pattern[i] ?? '').replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  }
  return new RegExp(`^${source}$`);
}

function categories(raw: string, table: Table): Set<string> {
  const parts = normalise(raw);
  const hits = new Set<string>();
  if (parts === null) return hits;
  for (const rule of table.rules) {
    if (!rule.hosts.some((h) => parts.host === h || parts.host.endsWith(`.${h}`))) continue;
    if (rule.category === 'union_host') hits.add('union_host');
    else if (rule.path_patterns.some((p) => globToRegExp(p).test(parts.path))) {
      hits.add(rule.category);
    }
  }
  return hits;
}

function decide(c: NavCase): Outcome {
  const { name, table } = tableFor(c.tables);
  const out = (action: string, notice: string | null, parseUrl: string | null = null) => ({
    action,
    notice,
    parse_url: parseUrl,
    table_used: name,
  });
  if (!/^https:/i.test(c.url)) return out('cancel', c.download ? 'download' : null);
  if (normalise(c.url) === null) return out('cancel', c.download ? 'download' : null);
  const hits = categories(c.url, table);
  if (hits.has('union_host')) {
    const topLevel = c.frame !== 'subframe';
    if (topLevel && hits.has('product') && c.switches.product_intercept && !c.basic_mode) {
      return out('parse', null, c.url.split('#')[0] ?? c.url);
    }
    if (c.switches.union_host_block ?? true) return out('block', 'union_host_blocked');
  }
  if (c.download) return out('cancel', 'download');
  return out('allow', null);
}

it('every navigation vector matches an independent reading of BR-ATTR-29 ②', () => {
  expect(vectors.navigation_cases.length).toBeGreaterThan(40);
  for (const c of vectors.navigation_cases) expect(decide(c), c.note).toEqual(c.expected);
});

it('the system browser exit is offered only for well-formed https pages that hit no category', () => {
  for (const c of vectors.open_in_browser_cases) {
    const { name, table } = tableFor(c.tables);
    const ok = normalise(c.url) !== null && categories(c.url, table).size === 0;
    expect({ can_open_in_browser: ok, table_used: name }, c.note).toEqual(c.expected);
  }
});

it('the vectors cover the cases 03 §5.1 and BR-ATTR-29 name', () => {
  const cases = vectors.navigation_cases;
  expect([...new Set(cases.map((c) => c.expected.action))].sort()).toEqual([
    'allow',
    'block',
    'cancel',
    'parse',
  ]);
  expect([...new Set(cases.map((c) => c.frame))].sort()).toEqual([
    'initial',
    'main',
    'new_window',
    'subframe',
  ]);
  expect([...new Set(cases.map((c) => c.expected.table_used))].sort()).toEqual([
    'bundled',
    'current',
    'last_good',
  ]);
  // While union_host_block is on (or unreadable), no platform page is ever allowed.
  for (const c of cases.filter((v) => v.switches.union_host_block !== false)) {
    if (categories(c.url, tableFor(c.tables).table).has('union_host')) {
      expect(c.expected.action, c.note).not.toBe('allow');
    }
  }
  expect(cases.some((c) => c.url.startsWith('intent://'))).toBe(true);
  expect(cases.some((c) => c.url.includes('@'))).toBe(true);
});
