// Self-consistency of specs/external-navigation.vectors.json (08 BR-ATTR-29 ② and 细则; 03 §5.1):
// an independent reading of the policy, written here with the WHATWG URL parser, must reach the
// expected outcome of every vector. The vectors were generated by another implementation; this
// test keeps the two in agreement and the file well-formed. The apps implement the policy
// themselves and run the same vectors.
import { readFileSync } from 'node:fs';
import { expect, it } from 'vitest';

type Rule = { platform: string; category: string; hosts: string[]; path_patterns: string[] };
type Table = { version: string; rules: Rule[] };
type TableName = 'current' | 'last_good' | 'bundled';
type Switches = { union_host_block: boolean | null; product_intercept: boolean };
type NavCase = {
  note: string;
  url: string;
  frame: 'initial' | 'main' | 'subframe' | 'new_window';
  switches: Switches;
  basic_mode: boolean;
  download: boolean;
  tables: TableName[];
  expected: { action: string; notice: string | null; table_used: TableName };
};
type BrowserCase = {
  note: string;
  url: string;
  tables: TableName[];
  expected: { can_open_in_browser: boolean; table_used: TableName };
};
type Vectors = {
  rule_tables: { current: Table; bundled: Table };
  navigation_cases: NavCase[];
  open_in_browser_cases: BrowserCase[];
};

const vectors = JSON.parse(
  readFileSync(new URL('../../../specs/external-navigation.vectors.json', import.meta.url), 'utf8'),
) as Vectors;

function tableFor(names: TableName[]): { name: TableName; table: Table } {
  // last_good, when present, is the same synthetic table as current (the vectors only vary which
  // tables exist); the bundled snapshot holds union_host domains only.
  const name = (['current', 'last_good', 'bundled'] as const).find((n) => names.includes(n));
  if (name === undefined) throw new Error('a case without any rule table');
  const table = name === 'bundled' ? vectors.rule_tables.bundled : vectors.rule_tables.current;
  return { name, table };
}

function globToRegExp(pattern: string): RegExp {
  let source = '';
  for (let i = 0; i < pattern.length; i++) {
    if (pattern.startsWith('**', i)) {
      source += '.*';
      i++;
    } else if (pattern[i] === '*') source += '[^/]*';
    else source += (pattern[i] ?? '').replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  }
  return new RegExp(`^${source}$`);
}

function categories(raw: string, table: Table): Set<string> {
  let url: URL;
  try {
    url = new URL(raw);
  } catch {
    return new Set();
  }
  if (url.protocol !== 'https:' || url.username !== '' || url.password !== '') return new Set();
  const host = url.hostname.replace(/\.$/, '').toLowerCase();
  const path = decodeURIComponent(url.pathname);
  const hits = new Set<string>();
  for (const rule of table.rules) {
    if (!rule.hosts.some((h) => host === h || host.endsWith(`.${h}`))) continue;
    if (rule.category === 'union_host') hits.add('union_host');
    else if (rule.path_patterns.some((p) => globToRegExp(p).test(path))) hits.add(rule.category);
  }
  return hits;
}

function decide(c: NavCase): NavCase['expected'] {
  const { name, table } = tableFor(c.tables);
  if (c.download) return { action: 'cancel', notice: 'download', table_used: name };
  if (!/^https:/i.test(c.url)) return { action: 'cancel', notice: null, table_used: name };
  const hits = categories(c.url, table);
  const blockOn = c.switches.union_host_block ?? true;
  if (!hits.has('union_host') || !blockOn)
    return { action: 'allow', notice: null, table_used: name };
  const topLevel = c.frame !== 'subframe';
  if (topLevel && hits.has('product') && c.switches.product_intercept && !c.basic_mode) {
    return { action: 'parse', notice: null, table_used: name };
  }
  return { action: 'block', notice: 'union_host_blocked', table_used: name };
}

it('every navigation vector matches an independent reading of BR-ATTR-29 ②', () => {
  expect(vectors.navigation_cases.length).toBeGreaterThan(20);
  for (const c of vectors.navigation_cases) expect(decide(c), c.note).toEqual(c.expected);
});

it('the system browser exit is offered only for https pages that hit no category', () => {
  for (const c of vectors.open_in_browser_cases) {
    const { name, table } = tableFor(c.tables);
    const ok = /^https:/i.test(c.url) && categories(c.url, table).size === 0;
    expect({ can_open_in_browser: ok, table_used: name }, c.note).toEqual(c.expected);
  }
});

it('the vectors cover the cases 03 §5.1 and BR-ATTR-29 name', () => {
  const actions = new Set(vectors.navigation_cases.map((c) => c.expected.action));
  expect([...actions].sort()).toEqual(['allow', 'block', 'cancel', 'parse']);
  const frames = new Set(vectors.navigation_cases.map((c) => c.frame));
  expect([...frames].sort()).toEqual(['initial', 'main', 'new_window', 'subframe']);
  const used = new Set(vectors.navigation_cases.map((c) => c.expected.table_used));
  expect([...used].sort()).toEqual(['bundled', 'current', 'last_good']);
  // Switching product interception off never turns a platform page into an allowed one.
  for (const c of vectors.navigation_cases.filter((v) => !v.switches.product_intercept)) {
    expect(c.expected.action, c.note).not.toBe('allow');
  }
  expect(vectors.navigation_cases.some((c) => c.url.startsWith('intent://'))).toBe(true);
});
