// Pure generators from contracts/design-tokens.json (规划/03 §10.1). No I/O here: the writing shell
// is scripts/generate.ts, and the drift tests call the same functions on the committed snapshot.
//
// Canonical CSS variable of a token = "--" + its path joined with "-"
// (color.background.canvas -> --color-background-canvas). Value spelling follows the planning
// repository's scripts/sync-brand.py so that tokens.gen.css matches design/tokens/variables.css.

/** Input is the complete contracts/design-tokens.json document, including metadata. */
export interface DesignTokens {
  schemaVersion: string;
  metadata: {
    version: string;
    cssFontBase: number;
    [key: string]: unknown;
  };
  tokens: Record<string, unknown>;
}

export interface TokenTheme {
  [key: string]: string | TokenTheme;
}

/** One leaf token, flattened in document order. */
interface TokenLeaf {
  path: string[];
  type: string;
  value: unknown;
  unit: unknown;
  variable: string;
}

const SEGMENT = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;
const HEX_COLOR = /^#[0-9A-F]{6}$/;
const BARE_FONT_FAMILY = /^-?[A-Za-z_][A-Za-z0-9_-]*$/;
const SHADOW_KEYS = ['blur', 'color', 'opacity', 'spread', 'x', 'y'];
/** Path segments that name prototype-chain members; rejected so no object's prototype is written. */
const RESERVED_SEGMENTS = new Set(['constructor', 'prototype', '__proto__']);

const HEADER = 'Generated by @couli/ui-tokens from contracts/design-tokens.json. Do not edit.';
const REGENERATE = 'Regenerate: node packages/ui-tokens/scripts/generate.ts';

function fail(message: string): never {
  throw new Error(`design tokens: ${message}`);
}

function isObject(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function finite(value: unknown, label: string): number {
  if (typeof value !== 'number' || !Number.isFinite(value)) fail(`${label}: expected a number`);
  return value;
}

/** Collects leaf tokens; a node with `type` or `value` is a token and must have both. */
function leaves(doc: DesignTokens): TokenLeaf[] {
  if (!isObject(doc) || !isObject(doc.tokens)) fail('expected a document with a tokens object');
  const result: TokenLeaf[] = [];
  const variables = new Set<string>();
  const walk = (node: unknown, path: string[]): void => {
    const label = path.join('.') || 'tokens';
    if (!isObject(node)) fail(`${label}: expected an object`);
    if ('type' in node || 'value' in node) {
      if (path.length === 0 || !('type' in node) || !('value' in node)) {
        fail(`${label}: a token needs both type and value`);
      }
      if (typeof node.type !== 'string') fail(`${label}: type must be a string`);
      const variable = `--${path.join('-')}`;
      if (variables.has(variable)) fail(`duplicate CSS variable ${variable}`);
      variables.add(variable);
      result.push({ path, type: node.type, value: node.value, unit: node.unit, variable });
      return;
    }
    const entries = Object.entries(node);
    if (entries.length === 0) fail(`${label}: empty token group`);
    for (const [segment, child] of entries) {
      // Checked before the segment syntax so the error names the full path; such keys would
      // otherwise reach Object / Object.prototype through the theme builder's plain objects.
      if (RESERVED_SEGMENTS.has(segment)) {
        fail(`${[...path, segment].join('.')}: reserved path segment ${JSON.stringify(segment)}`);
      }
      if (!SEGMENT.test(segment)) fail(`${label}: invalid path segment ${JSON.stringify(segment)}`);
      walk(child, [...path, segment]);
    }
  };
  walk(doc.tokens, []);
  return result;
}

/** Same spelling as sync-brand.py numeric_text: no exponent, no trailing zeros. */
function numericText(value: number): string {
  let text = String(Object.is(value, -0) ? 0 : value);
  const exponent = /^(-?)(\d+)(?:\.(\d+))?e([+-]\d+)$/.exec(text);
  if (exponent) {
    const [, sign, whole = '', fraction = '', power = '0'] = exponent;
    const digits = whole + fraction;
    const point = whole.length + Number(power);
    const body =
      point <= 0
        ? `0.${'0'.repeat(-point)}${digits}`
        : point >= digits.length
          ? digits + '0'.repeat(point - digits.length)
          : `${digits.slice(0, point)}.${digits.slice(point)}`;
    text = sign + body.replace(/^0+(?=\d)/, '');
  }
  return text.includes('.') ? text.replace(/0+$/, '').replace(/\.$/, '') : text;
}

function hasControlCharacter(text: string): boolean {
  return [...text].some((char) => {
    const code = char.codePointAt(0) ?? 0;
    return code < 32 || code === 127;
  });
}

function color(value: unknown, label: string): string {
  if (typeof value !== 'string' || !HEX_COLOR.test(value)) {
    fail(`${label}: expected an uppercase #RRGGBB color`);
  }
  return value;
}

function cssValue(leaf: TokenLeaf, fontBase: number): string {
  const label = leaf.path.join('.');
  const { type, value } = leaf;
  switch (type) {
    case 'color':
      return color(value, label);
    case 'dimension':
    case 'fontSize': {
      if (leaf.unit !== 'logical') fail(`${label}: expected unit "logical"`);
      const size = finite(value, label);
      if (size < 0 || (type === 'fontSize' && size === 0)) fail(`${label}: out of range`);
      return type === 'fontSize' ? `${numericText(size / fontBase)}rem` : `${numericText(size)}px`;
    }
    case 'lineHeight': {
      const height = finite(value, label);
      if (height <= 0) fail(`${label}: must be positive`);
      return numericText(height);
    }
    case 'fontWeight': {
      const weight = finite(value, label);
      if (weight < 1 || weight > 1000) fail(`${label}: must be within 1..1000`);
      return numericText(weight);
    }
    case 'fontFamily': {
      if (!Array.isArray(value) || value.length === 0) fail(`${label}: expected a family list`);
      return value
        .map((family: unknown) => {
          if (typeof family !== 'string' || family === '' || hasControlCharacter(family)) {
            fail(`${label}: invalid font family`);
          }
          if (BARE_FONT_FAMILY.test(family)) return family;
          return `"${family.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;
        })
        .join(', ');
    }
    case 'shadow': {
      if (!Array.isArray(value)) fail(`${label}: expected a shadow list`);
      if (value.length === 0) return 'none';
      return value
        .map((layer: unknown, index) => {
          const at = `${label}[${index}]`;
          if (!isObject(layer) || Object.keys(layer).sort().join() !== SHADOW_KEYS.join()) {
            fail(`${at}: expected x/y/blur/spread/color/opacity`);
          }
          const lengths = (['x', 'y', 'blur', 'spread'] as const).map((key) => {
            const length = finite(layer[key], `${at}.${key}`);
            if (key === 'blur' && length < 0) fail(`${at}.blur: must be >= 0`);
            return `${numericText(length)}px`;
          });
          const hex = color(layer.color, `${at}.color`);
          const rgb = [1, 3, 5].map((i) => String(parseInt(hex.slice(i, i + 2), 16))).join(', ');
          const opacity = finite(layer.opacity, `${at}.opacity`);
          if (opacity < 0 || opacity > 1) fail(`${at}.opacity: must be within 0..1`);
          return `${lengths.join(' ')} rgba(${rgb}, ${numericText(opacity)})`;
        })
        .join(', ');
    }
    default:
      return fail(`${label}: unsupported token type ${JSON.stringify(type)}`);
  }
}

function fontBase(doc: DesignTokens): number {
  const base = isObject(doc.metadata) ? doc.metadata.cssFontBase : undefined;
  const value = finite(base, 'metadata.cssFontBase');
  if (value <= 0) fail('metadata.cssFontBase: must be positive');
  return value;
}

/**
 * `:root` with every leaf token, MVP light only (TECH-22: forced light even when the system is
 * dark). The rule is prettier-ignored so colors keep their canonical uppercase spelling and font
 * family names keep double quotes, exactly as in the planning variables.css.
 */
export function generateTokensCss(tokens: DesignTokens): string {
  const base = fontBase(tokens);
  const lines = leaves(tokens).map((leaf) => `  ${leaf.variable}: ${cssValue(leaf, base)};`);
  return [
    `/* ${HEADER} */`,
    `/* ${REGENERATE} */`,
    '/* prettier-ignore */',
    ':root {',
    '  color-scheme: only light;',
    ...lines,
    '}',
    '',
  ].join('\n');
}

/** Tailwind 4 namespace and the token path prefix it already implies. */
function tailwindNamespace(leaf: TokenLeaf): { namespace: string; implied: string[] } {
  switch (leaf.type) {
    case 'color':
      return { namespace: 'color', implied: ['color'] };
    case 'fontFamily':
      return { namespace: 'font', implied: ['font', 'family'] };
    case 'fontSize':
      return { namespace: 'text', implied: ['font', 'size'] };
    case 'lineHeight':
      return { namespace: 'leading', implied: ['font', 'line-height'] };
    case 'fontWeight':
      return { namespace: 'font-weight', implied: ['font', 'weight'] };
    case 'shadow':
      return { namespace: 'shadow', implied: ['shadow'] };
    case 'dimension':
      return leaf.path[0] === 'radius'
        ? { namespace: 'radius', implied: ['radius'] }
        : { namespace: 'spacing', implied: ['space'] };
    default:
      return fail(`${leaf.path.join('.')}: unsupported token type ${JSON.stringify(leaf.type)}`);
  }
}

/**
 * Tailwind alias = --<namespace>-couli-<path without the implied prefix>. The `couli` segment
 * keeps aliases distinct from the canonical variables (no self reference such as
 * --color-brand-primary: var(--color-brand-primary)) and from Tailwind's default theme keys.
 */
function tailwindAlias(leaf: TokenLeaf): string {
  const { namespace, implied } = tailwindNamespace(leaf);
  const rest = implied.every((segment, i) => leaf.path[i] === segment)
    ? leaf.path.slice(implied.length)
    : leaf.path;
  return `--${[namespace, 'couli', ...rest].join('-')}`;
}

/**
 * Tailwind 4 `@theme inline` block: utilities resolve straight to the canonical variables from
 * tokens.css (import both). Values are only var() references, never literals.
 */
export function generateTailwindCss(tokens: DesignTokens): string {
  const seen = new Set<string>();
  const lines = leaves(tokens).map((leaf) => {
    const alias = tailwindAlias(leaf);
    if (seen.has(alias)) fail(`duplicate Tailwind alias ${alias}`);
    seen.add(alias);
    return `  ${alias}: var(${leaf.variable});`;
  });
  return [
    `/* ${HEADER} */`,
    `/* ${REGENERATE} */`,
    '/* Needs @couli/ui-tokens/tokens.css for the referenced variables. */',
    '@theme inline {',
    ...lines,
    '}',
    '',
  ].join('\n');
}

/** Every theme leaf references a canonical CSS variable, without literal values. */
export function themeFromTokens(tokens: DesignTokens): TokenTheme {
  const theme: TokenTheme = {};
  for (const leaf of leaves(tokens)) {
    let node = theme;
    for (const segment of leaf.path.slice(0, -1)) {
      // Own properties only: leaves() already rejects prototype member names; this keeps
      // inherited members from ever being treated as a group.
      const child = Object.hasOwn(node, segment) ? node[segment] : undefined;
      if (typeof child === 'string') fail(`${leaf.path.join('.')}: token nested under a token`);
      node = child ?? (node[segment] = {});
    }
    node[leaf.path.at(-1)!] = `var(${leaf.variable})`;
  }
  return theme;
}

const IDENTIFIER = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

function serialize(theme: TokenTheme, indent: string): string[] {
  const lines: string[] = [];
  for (const [key, value] of Object.entries(theme)) {
    const name = IDENTIFIER.test(key) ? key : `'${key}'`;
    if (typeof value === 'string') {
      lines.push(`${indent}${name}: '${value}',`);
    } else {
      lines.push(`${indent}${name}: {`, ...serialize(value, `${indent}  `), `${indent}},`);
    }
  }
  return lines;
}

/** Pure serializer shared by the writing shell and the byte-for-byte drift check. */
export function generateThemeTs(tokens: DesignTokens): string {
  return [
    `// ${HEADER}`,
    `// ${REGENERATE}`,
    '// Each leaf is a var() reference to the canonical variable in tokens.css.',
    'export const tokenTheme = {',
    ...serialize(themeFromTokens(tokens), '  '),
    '} as const;',
    '',
  ].join('\n');
}
