// Generated by @couli/ui-tokens from contracts/design-tokens.json. Do not edit.
// Regenerate: node packages/ui-tokens/scripts/generate.ts
// Each leaf is a var() reference to the canonical variable in tokens.css.
export const tokenTheme = {
  color: {
    brand: {
      primary: 'var(--color-brand-primary)',
      emphasis: 'var(--color-brand-emphasis)',
      secondary: 'var(--color-brand-secondary)',
      subtle: 'var(--color-brand-subtle)',
    },
    background: {
      canvas: 'var(--color-background-canvas)',
      'admin-canvas': 'var(--color-background-admin-canvas)',
      surface: 'var(--color-background-surface)',
      muted: 'var(--color-background-muted)',
      placeholder: 'var(--color-background-placeholder)',
    },
    text: {
      primary: 'var(--color-text-primary)',
      secondary: 'var(--color-text-secondary)',
      inverse: 'var(--color-text-inverse)',
      link: 'var(--color-text-link)',
    },
    price: {
      text: 'var(--color-price-text)',
    },
    rebate: {
      text: 'var(--color-rebate-text)',
      background: 'var(--color-rebate-background)',
      solid: {
        background: 'var(--color-rebate-solid-background)',
        text: 'var(--color-rebate-solid-text)',
      },
    },
    status: {
      pending: {
        text: 'var(--color-status-pending-text)',
        background: 'var(--color-status-pending-background)',
      },
      success: {
        text: 'var(--color-status-success-text)',
        background: 'var(--color-status-success-background)',
      },
      warning: {
        text: 'var(--color-status-warning-text)',
        background: 'var(--color-status-warning-background)',
      },
      error: {
        text: 'var(--color-status-error-text)',
        background: 'var(--color-status-error-background)',
      },
    },
    border: {
      subtle: 'var(--color-border-subtle)',
      control: 'var(--color-border-control)',
    },
    focus: {
      ring: 'var(--color-focus-ring)',
    },
    source: {
      text: 'var(--color-source-text)',
      background: 'var(--color-source-background)',
      border: 'var(--color-source-border)',
    },
    button: {
      primary: {
        default: {
          background: 'var(--color-button-primary-default-background)',
          text: 'var(--color-button-primary-default-text)',
        },
        pressed: {
          background: 'var(--color-button-primary-pressed-background)',
          text: 'var(--color-button-primary-pressed-text)',
        },
        disabled: {
          background: 'var(--color-button-primary-disabled-background)',
          text: 'var(--color-button-primary-disabled-text)',
        },
      },
    },
  },
  font: {
    family: {
      system: 'var(--font-family-system)',
    },
    size: {
      caption: 'var(--font-size-caption)',
      footnote: 'var(--font-size-footnote)',
      body: 'var(--font-size-body)',
      title: 'var(--font-size-title)',
      heading: 'var(--font-size-heading)',
      display: 'var(--font-size-display)',
    },
    'line-height': {
      caption: 'var(--font-line-height-caption)',
      footnote: 'var(--font-line-height-footnote)',
      body: 'var(--font-line-height-body)',
      title: 'var(--font-line-height-title)',
      heading: 'var(--font-line-height-heading)',
      display: 'var(--font-line-height-display)',
    },
    weight: {
      regular: 'var(--font-weight-regular)',
      medium: 'var(--font-weight-medium)',
      semibold: 'var(--font-weight-semibold)',
      bold: 'var(--font-weight-bold)',
    },
  },
  space: {
    '0': 'var(--space-0)',
    '1': 'var(--space-1)',
    '2': 'var(--space-2)',
    '3': 'var(--space-3)',
    '4': 'var(--space-4)',
    '5': 'var(--space-5)',
    '6': 'var(--space-6)',
    '8': 'var(--space-8)',
    '10': 'var(--space-10)',
    '12': 'var(--space-12)',
    '16': 'var(--space-16)',
  },
  radius: {
    small: 'var(--radius-small)',
    button: 'var(--radius-button)',
    card: 'var(--radius-card)',
    panel: 'var(--radius-panel)',
    pill: 'var(--radius-pill)',
  },
  shadow: {
    none: 'var(--shadow-none)',
    card: 'var(--shadow-card)',
    floating: 'var(--shadow-floating)',
  },
  focus: {
    width: 'var(--focus-width)',
    offset: 'var(--focus-offset)',
  },
  interaction: {
    target: {
      minimum: 'var(--interaction-target-minimum)',
      ios: 'var(--interaction-target-ios)',
      android: 'var(--interaction-target-android)',
      harmony: 'var(--interaction-target-harmony)',
    },
  },
  component: {
    button: {
      'min-height': 'var(--component-button-min-height)',
      'padding-inline': 'var(--component-button-padding-inline)',
      'padding-block': 'var(--component-button-padding-block)',
      gap: 'var(--component-button-gap)',
    },
    control: {
      'min-height': 'var(--component-control-min-height)',
      'border-width': 'var(--component-control-border-width)',
    },
    icon: {
      default: 'var(--component-icon-default)',
    },
  },
} as const;
