// PG admission contracts and pure quota rules (BR-AI-15 / BR-AI-23).
import { FixedClock } from '../../../platform/index.ts';
import type { DoneData, ErrorData } from '../writer/index.ts';

export type QuotaSubject =
  | { readonly tier: 'member'; readonly userId: string }
  | {
      readonly tier: 'guest';
      readonly loggedIn: boolean;
      readonly deviceHash: string;
      readonly ipKey: string;
    };

export interface AdmissionLimits {
  readonly memberDaily: number;
  readonly guestDaily: number;
  readonly guestIpDaily: number;
  readonly perMinute: number;
  readonly maxRounds: number;
}

declare const redacted: unique symbol;
/** Text after the BR-AI-19 redaction; only the redaction function produces one (design §2.4). */
export type RedactedText = string & { readonly [redacted]: true };

export interface AdmissionReply {
  /** The assistant message id (agent_messages, text NULL at acceptance). */
  readonly assistantMessageId: string;
  readonly promptVersion: string;
  readonly modelSnapshot: string | null;
  /** agent_runs.user_text. */
  readonly runUserText: RedactedText | null;
  /** agent_messages.text of the user row. */
  readonly messageText: RedactedText | null;
}

export interface AdmissionRequest {
  readonly sessionId: string;
  readonly clientMsgId: string;
  readonly runId: string;
  /** The user message id (agent_messages), generated by the caller like runId. */
  readonly messageId: string;
  readonly subject: QuotaSubject;
  readonly reply: AdmissionReply;
}

export interface AdmissionTicket {
  readonly runId: string;
  /** The user message id (agent_messages), generated by the caller like runId. */
  readonly messageId: string;
  readonly sessionId: string;
  readonly subject: QuotaSubject;
  readonly dayKey: string;
  readonly acceptedAtMs: number;
  readonly lockExpiresAtMs: number;
}

export type NextStep = 'login' | 'bind_phone' | 'none';

/** Persisted terminal frame (agent_runs.final_event) in its in-memory form. */
export type AdmissionFrame =
  | { readonly event: 'done'; readonly data: DoneData }
  | { readonly event: 'error'; readonly data: ErrorData };

/** The original acceptance of a duplicate (04 §8.1 「重复消息」), every field read from PG. */
export interface OriginalRun {
  readonly runId: string;
  readonly userMessageId: string;
  readonly assistantMessageId: string;
  readonly promptVersion: string;
  readonly modelSnapshot: string | null;
}

export type DuplicateReply =
  { readonly kind: 'final'; readonly frame: AdmissionFrame } | { readonly kind: 'running' };

export type AdmissionResult =
  | { readonly kind: 'accepted'; readonly ticket: AdmissionTicket; readonly quotaLeft: number }
  | { readonly kind: 'duplicate'; readonly original: OriginalRun; readonly reply: DuplicateReply }
  | { readonly kind: 'rejected'; readonly code: 30506 }
  | { readonly kind: 'rejected'; readonly code: 42901; readonly retryAfterSeconds: number }
  | {
      readonly kind: 'rejected';
      readonly code: 30504;
      readonly reason: 'round_limit' | 'expired';
    }
  | {
      readonly kind: 'rejected';
      readonly code: 30502;
      readonly resetAt: string;
      readonly next: NextStep;
    };

export type RunEnding =
  | 'stop'
  | 'fallback'
  | 'budget'
  | 'auth_required'
  | 'safety'
  | 'limit'
  | 'client_error'
  | 'cancelled'
  | 'disconnected'
  | 'consent_withdrawn'
  | 'timeout'
  | 'disabled'
  | 'input_review_timeout'
  | 'server_error';

export interface RunOutcome {
  readonly ending: RunEnding;
  readonly cardsDelivered: number;
}

export interface SettleResult {
  readonly refunded: boolean;
  readonly quotaLeft: number;
}

export interface Admission {
  admit(req: AdmissionRequest, limits: AdmissionLimits): Promise<AdmissionResult>;
  settle(
    ticket: AdmissionTicket,
    outcome: RunOutcome,
    limits: AdmissionLimits,
  ): Promise<SettleResult>;
}

export class AdmissionUnavailableError extends Error {
  /** 'rolled_back': nothing committed; 'unknown': the COMMIT outcome could not be read back. */
  readonly outcome: 'rolled_back' | 'unknown';

  constructor(outcome: 'rolled_back' | 'unknown') {
    super(outcome);
    this.name = 'AdmissionUnavailableError';
    this.outcome = outcome;
  }
}

/** A run of the session is held for manual handling (finalize_hold): JSON 50001. */
export class AdmissionHeldError extends Error {}

/** The +08:00 day `dayKey` as [start, end) instants (design §1.4). */
export function dayRange(dayKey: string): { readonly start: Date; readonly end: Date } {
  // Parse the supplied civil date through the clock module; never consult wall-clock time.
  const start = new FixedClock(`${dayKey}T00:00:00+08:00`).now();
  if (!Number.isFinite(start.getTime()) || dayKeyOf(start) !== dayKey) {
    throw new RangeError('Invalid quota day');
  }
  const end = structuredClone(start);
  end.setTime(start.getTime() + DAY_MS);
  return { start, end };
}

export function admissionDefaults(): AdmissionLimits {
  return { memberDaily: 30, guestDaily: 3, guestIpDaily: 30, perMinute: 10, maxRounds: 30 };
}

export function shouldRefund(outcome: RunOutcome): boolean {
  return (
    outcome.cardsDelivered === 0 &&
    ['server_error', 'disabled', 'timeout', 'input_review_timeout'].includes(outcome.ending)
  );
}

const DAY_MS = 86_400_000;
// Quota days are civil dates, not ledger accounting dates. Format only the supplied instant.
const DAY_FORMAT = new Intl.DateTimeFormat('en-US', {
  timeZone: '+08:00',
  calendar: 'gregory',
  numberingSystem: 'latn',
  year: 'numeric',
  month: '2-digit',
  day: '2-digit',
});

function formatDay(ms: number): string {
  const parts = DAY_FORMAT.formatToParts(ms);
  const part = (type: string) => parts.find((p) => p.type === type)!.value;
  return `${part('year').padStart(4, '0')}-${part('month')}-${part('day')}`;
}

export function dayKeyOf(now: Date): string {
  return formatDay(now.getTime());
}

export function nextResetAt(now: Date): string {
  return `${formatDay(now.getTime() + DAY_MS)}T00:00:00+08:00`;
}

export function nextStepOf(subject: QuotaSubject): NextStep {
  return subject.tier === 'member' ? 'none' : subject.loggedIn ? 'bind_phone' : 'login';
}

// JSON tuples preserve opaque identifiers (including separators) without key collisions.
function key(...parts: string[]): string {
  return JSON.stringify(parts);
}

function subjectKeys(subject: QuotaSubject): string[] {
  return subject.tier === 'member'
    ? [key('member', subject.userId)]
    : [key('device', subject.deviceHash), key('ip', subject.ipKey)];
}

export { subjectKeys };
