// Generates db/migrations/0002_pgboss-schema-v42.sql from the installed pg-boss
// (ADR-0001 §4.2 #14). Deterministic: the same pg-boss version always yields the same file.
//
//   node scripts/gen-pgboss-migration.ts           write the file
//   node scripts/gen-pgboss-migration.ts --check   compare with the committed file (exit 1 on drift)
//
// Only the first installation is generated here. Upgrading pg-boss needs a NEW migration built
// from getMigrationPlans('pgboss', <old version>); never regenerate an applied migration.
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import path from 'node:path';

import { getConstructionPlans } from 'pg-boss';

import { MIGRATIONS_DIR } from '../src/testing/provision.ts';
import { cliArgs, fail, info, main } from './util.ts';

const SCHEMA = 'pgboss';
/** Schema version the committed migration installs; the file name carries it. */
const EXPECTED_SCHEMA_VERSION = 42;
export const PGBOSS_MIGRATION_FILE = path.join(
  MIGRATIONS_DIR,
  `0002_pgboss-schema-v${String(EXPECTED_SCHEMA_VERSION)}.sql`,
);

function installedPgBossVersion(): string {
  const require = createRequire(import.meta.url);
  const entry = require.resolve('pg-boss');
  // <pkg>/dist/index.js -> <pkg>/package.json
  const manifest = path.join(path.dirname(entry), '..', 'package.json');
  const parsed: unknown = JSON.parse(readFileSync(manifest, 'utf8'));
  if (
    typeof parsed !== 'object' ||
    parsed === null ||
    !('name' in parsed) ||
    parsed.name !== 'pg-boss' ||
    !('version' in parsed) ||
    typeof parsed.version !== 'string'
  ) {
    throw new Error(`cannot read the pg-boss version from ${manifest}`);
  }
  return parsed.version;
}

/** Removes the single line that consists of `statement` and fails unless there is exactly one. */
function removeSingleLine(sql: string, statement: 'BEGIN;' | 'COMMIT;'): string {
  const lines = sql.split('\n');
  const hits = lines.filter((line) => line.trim() === statement);
  if (hits.length !== 1) {
    throw new Error(
      `expected exactly one "${statement}" line in the pg-boss plan, found ${String(hits.length)}`,
    );
  }
  return lines.filter((line) => line.trim() !== statement).join('\n');
}

export function renderPgBossMigration(): string {
  const version = installedPgBossVersion();
  const plan = getConstructionPlans(SCHEMA);

  const versionMatch = /INSERT INTO pgboss\.version\(version\) VALUES \('(\d+)'\)/.exec(plan);
  const schemaVersion = versionMatch?.[1] === undefined ? Number.NaN : Number(versionMatch[1]);
  if (schemaVersion !== EXPECTED_SCHEMA_VERSION) {
    throw new Error(
      `pg-boss ${version} installs schema version ${String(schemaVersion)}, but this generator ` +
        `is pinned to ${String(EXPECTED_SCHEMA_VERSION)}. An upgrade needs a new migration from ` +
        `getMigrationPlans (ADR-0001 §4.2 #14).`,
    );
  }
  if (/^--\s*(Up|Down) Migration/im.test(plan)) {
    throw new Error('the pg-boss plan contains a node-pg-migrate marker line');
  }

  // node-pg-migrate runs every pending migration in one outer transaction; the plan's own
  // BEGIN / COMMIT would end that transaction early.
  const body = removeSingleLine(removeSingleLine(plan, 'BEGIN;'), 'COMMIT;');

  const header = [
    '-- Up Migration',
    `-- pg-boss ${version}, schema version ${String(schemaVersion)}: first installation of schema "${SCHEMA}".`,
    '-- GENERATED by packages/db/scripts/gen-pgboss-migration.ts from getConstructionPlans(); do',
    '-- not edit by hand. The plan is copied verbatim except that its BEGIN; and COMMIT; lines',
    '-- are removed (ADR-0001 §4.2 #14); the statements after the plan (see the end of this file)',
    '-- are added by the generator. Processes start pg-boss with migrate:false.',
    '-- Compatibility: additive. Recovery: restore from backup (no down migrations in this repo).',
    '',
  ].join('\n');

  const footer = [
    '',
    '-- The plan sets these for its own installation; put the defaults back for the migrations',
    '-- that follow in the same outer transaction.',
    'SET LOCAL lock_timeout = DEFAULT;',
    'SET LOCAL idle_in_transaction_session_timeout = DEFAULT;',
    '',
    '-- The plan creates queue_stats partitions for the installation day and the day after',
    '-- (pgboss.job_now()), so the installed schema would depend on the date. They are only used',
    '-- with persistQueueStats, which this project keeps off (ADR-0001 §4.2 #14). Drop them again:',
    '-- every environment gets the same schema and db/schema.sql stays stable.',
    'DO $$',
    'DECLARE',
    '  v_partition text;',
    'BEGIN',
    '  FOR v_partition IN',
    '    SELECT c.relname',
    '    FROM pg_catalog.pg_inherits i',
    '    JOIN pg_catalog.pg_class c ON c.oid = i.inhrelid',
    `    WHERE i.inhparent = '${SCHEMA}.queue_stats'::regclass`,
    '  LOOP',
    `    EXECUTE format('DROP TABLE ${SCHEMA}.%I', v_partition);`,
    '  END LOOP;',
    'END',
    '$$;',
    '',
    '-- Business roles only read and write the queue tables; they never own or alter the schema.',
    `GRANT USAGE ON SCHEMA ${SCHEMA} TO couli_app, couli_payout;`,
    `GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA ${SCHEMA} TO couli_app, couli_payout;`,
    '',
  ].join('\n');

  return `${header}${body.replace(/\s+$/, '')}\n${footer}`;
}

/** Returns null when the committed file matches, otherwise a description of the drift. */
export function checkPgBossMigration(): string | null {
  if (!existsSync(PGBOSS_MIGRATION_FILE)) {
    return `${PGBOSS_MIGRATION_FILE} does not exist`;
  }
  const committed = readFileSync(PGBOSS_MIGRATION_FILE, 'utf8');
  return committed === renderPgBossMigration()
    ? null
    : `${PGBOSS_MIGRATION_FILE} differs from the plan of the installed pg-boss`;
}

if (import.meta.main) {
  await main(() => {
    const args = cliArgs();
    const unknown = args.filter((arg) => arg !== '--check');
    if (unknown.length > 0) {
      fail(`未知参数：${unknown.join(' ')}。用法：gen-pgboss-migration.ts [--check]`);
    }
    if (args.includes('--check')) {
      const drift = checkPgBossMigration();
      if (drift !== null) {
        fail(
          `pg-boss 迁移文件与已安装的 pg-boss 不一致：${drift}。` +
            '已合并的迁移不能重新生成；升级 pg-boss 要另写迁移（ADR-0001 §4.2 第 14 项）。',
          1,
        );
      }
      info('pg-boss 迁移文件与已安装的 pg-boss 一致。');
      return;
    }
    writeFileSync(PGBOSS_MIGRATION_FILE, renderPgBossMigration());
    info(`已生成 ${PGBOSS_MIGRATION_FILE}`);
  });
}
